/* ===================== TRACKS ===================== */
// id: [name, location, type, length (miles), rain chance]. Types: ss superspeedway/drafting, int intermediate oval, sht short/flat oval, dirt, road, street, kart, drag.
const TRK={
 // NASCAR / US ovals
 daytona:["Daytona International Speedway","Daytona Beach, FL","ss",2.5,.12],talladega:["Talladega Superspeedway","Lincoln, AL","ss",2.66,.12],atlanta:["EchoPark Speedway","Hampton, GA","ss",1.54,.14],
 lasvegas:["Las Vegas Motor Speedway","Las Vegas, NV","int",1.5,.03],charlotte:["Charlotte Motor Speedway","Concord, NC","int",1.5,.15],texas:["Texas Motor Speedway","Fort Worth, TX","int",1.5,.1],kansas:["Kansas Speedway","Kansas City, KS","int",1.5,.12],
 homestead:["Homestead-Miami Speedway","Homestead, FL","int",1.5,.15],chicagoland:["Chicagoland Speedway","Joliet, IL","int",1.5,.12],michigan:["Michigan International Speedway","Brooklyn, MI","int",2.0,.14],pocono:["Pocono Raceway","Long Pond, PA","int",2.5,.16],
 indy:["Indianapolis Motor Speedway","Speedway, IN","int",2.5,.12],darlington:["Darlington Raceway","Darlington, SC","int",1.366,.12],nashville:["Nashville Superspeedway","Lebanon, TN","int",1.33,.13],
 dover:["Dover Motor Speedway","Dover, DE","sht",1.0,.14],phoenix:["Phoenix Raceway","Avondale, AZ","sht",1.0,.02],newhampshire:["New Hampshire Motor Speedway","Loudon, NH","sht",1.058,.15],richmond:["Richmond Raceway","Richmond, VA","sht",0.75,.12],
 martinsville:["Martinsville Speedway","Ridgeway, VA","sht",0.526,.12],bristol:["Bristol Motor Speedway","Bristol, TN","sht",0.533,.12],nwilkesboro:["North Wilkesboro Speedway","North Wilkesboro, NC","sht",0.625,.13],iowa:["Iowa Speedway","Newton, IA","sht",0.875,.12],
 gateway:["World Wide Technology Raceway","Madison, IL","sht",1.25,.12],milwaukee:["Milwaukee Mile","West Allis, WI","sht",1.0,.12],rockingham:["Rockingham Speedway","Rockingham, NC","sht",1.017,.12],irp:["Lucas Oil Indianapolis Raceway Park","Brownsburg, IN","sht",0.686,.12],
 fiveflags:["Five Flags Speedway","Pensacola, FL","sht",0.5,.1],toledo:["Toledo Speedway","Toledo, OH","sht",0.5,.12],salem:["Salem Speedway","Salem, IN","sht",0.555,.12],berlin:["Berlin Raceway","Marne, MI","sht",0.4375,.12],elko:["Elko Speedway","Elko New Market, MN","sht",0.375,.12],
 springfield:["Illinois State Fairgrounds (dirt mile)","Springfield, IL","dirt",1.0,.12],duquoin:["DuQuoin State Fairgrounds (dirt mile)","Du Quoin, IL","dirt",1.0,.12],charlotteq:["Charlotte Motor Speedway quarter-mile","Concord, NC","sht",0.25,.15],
 // US road & street
 cota:["Circuit of the Americas","Austin, TX","road",3.41,.06],glen:["Watkins Glen International","Watkins Glen, NY","road",2.45,.18],sonoma:["Sonoma Raceway","Sonoma, CA","road",1.99,.04],roval:["Charlotte Motor Speedway ROVAL","Concord, NC","road",2.28,.15],
 sandiego:["Naval Base Coronado street course","San Diego, CA","street",3.4,.03],limerock:["Lime Rock Park","Lakeville, CT","road",1.5,.18],roadamerica:["Road America","Elkhart Lake, WI","road",4.05,.2],midohio:["Mid-Ohio Sports Car Course","Lexington, OH","road",2.26,.18],
 barber:["Barber Motorsports Park","Birmingham, AL","road",2.38,.15],laguna:["WeatherTech Raceway Laguna Seca","Monterey, CA","road",2.24,.05],portland:["Portland International Raceway","Portland, OR","road",1.96,.15],imsrc:["Indianapolis Motor Speedway road course","Speedway, IN","road",2.44,.15],
 stpete:["Streets of St. Petersburg","St. Petersburg, FL","street",1.8,.12],longbeach:["Streets of Long Beach","Long Beach, CA","street",1.97,.03],detroit:["Streets of Detroit","Detroit, MI","street",1.65,.15],arlington:["Streets of Arlington","Arlington, TX","street",2.7,.1],
 markham:["Streets of Markham","Markham, ON","street",1.8,.15],washington:["Streets of Washington, D.C.","Washington, D.C.","street",2.0,.15],sebring:["Sebring International Raceway","Sebring, FL","road",3.74,.15],roadatlanta:["Michelin Raceway Road Atlanta","Braselton, GA","road",2.54,.15],
 vir:["VIRginia International Raceway","Alton, VA","road",3.27,.15],ctmp:["Canadian Tire Motorsport Park","Bowmanville, ON","road",2.46,.18],pitt:["Pittsburgh International Race Complex","Wampum, PA","road",2.78,.18],nola:["NOLA Motorsports Park","Avondale, LA","road",2.75,.18],
 // F1 / international
 albert:["Albert Park Circuit","Melbourne, Australia","street",3.28,.15],shanghai:["Shanghai International Circuit","Shanghai, China","road",3.39,.2],suzuka:["Suzuka Circuit","Suzuka, Japan","road",3.61,.25],bahrain:["Bahrain International Circuit","Sakhir, Bahrain","road",3.36,.01],
 jeddah:["Jeddah Corniche Circuit","Jeddah, Saudi Arabia","street",3.84,.01],miami:["Miami International Autodrome","Miami Gardens, FL","street",3.36,.15],montreal:["Circuit Gilles Villeneuve","Montreal, Canada","street",2.71,.25],monaco:["Circuit de Monaco","Monte Carlo, Monaco","street",2.07,.12],
 barcelona:["Circuit de Barcelona-Catalunya","Montmeló, Spain","road",2.89,.08],redbullring:["Red Bull Ring","Spielberg, Austria","road",2.68,.25],silverstone:["Silverstone Circuit","Silverstone, UK","road",3.66,.3],spa:["Circuit de Spa-Francorchamps","Stavelot, Belgium","road",4.35,.35],
 hungaroring:["Hungaroring","Mogyoród, Hungary","road",2.72,.12],zandvoort:["Circuit Zandvoort","Zandvoort, Netherlands","road",2.65,.25],monza:["Autodromo Nazionale Monza","Monza, Italy","road",3.6,.15],madrid:["Madring","Madrid, Spain","street",3.39,.06],
 baku:["Baku City Circuit","Baku, Azerbaijan","street",3.73,.05],singapore:["Marina Bay Street Circuit","Singapore","street",3.07,.2],mexico:["Autódromo Hermanos Rodríguez","Mexico City, Mexico","road",2.67,.1],interlagos:["Autódromo José Carlos Pace (Interlagos)","São Paulo, Brazil","road",2.68,.35],
 vegas:["Las Vegas Strip Circuit","Las Vegas, NV","street",3.85,.01],lusail:["Lusail International Circuit","Lusail, Qatar","road",3.37,.01],yasmarina:["Yas Marina Circuit","Abu Dhabi, UAE","road",3.28,.01],imola:["Imola (Enzo e Dino Ferrari)","Imola, Italy","road",3.05,.25],
 misano:["Misano World Circuit","Misano Adriatico, Italy","road",2.6,.15],mugello:["Mugello Circuit","Scarperia, Italy","road",3.26,.15],vallelunga:["Vallelunga Circuit","Campagnano di Roma, Italy","road",2.53,.15],paulricard:["Circuit Paul Ricard","Le Castellet, France","road",3.6,.08],
 lemans:["Circuit de la Sarthe","Le Mans, France","road",8.47,.3],fuji:["Fuji Speedway","Oyama, Japan","road",2.84,.3],brands:["Brands Hatch","West Kingsdown, UK","road",1.2,.3],hockenheim:["Hockenheimring","Hockenheim, Germany","road",2.84,.2],
 // Formula E
 fe_mexico:["Mexico City E-Prix circuit","Mexico City, Mexico","street",1.46,.05],fe_miami:["Homestead-Miami E-Prix circuit","Homestead, FL","street",2.0,.15],fe_jeddah:["Jeddah Corniche E-Prix circuit","Jeddah, Saudi Arabia","street",1.86,.01],fe_madrid:["Jarama E-Prix circuit","Madrid, Spain","street",2.4,.05],
 fe_monaco:["Monaco E-Prix circuit","Monte Carlo, Monaco","street",2.07,.1],fe_berlin:["Tempelhof Airport Street Circuit","Berlin, Germany","street",1.47,.2],fe_tokyo:["Tokyo Street Circuit","Tokyo, Japan","street",1.6,.2],fe_shanghai:["Shanghai E-Prix circuit","Shanghai, China","street",2.0,.2],
 fe_jakarta:["Jakarta International E-Prix Circuit","Jakarta, Indonesia","street",1.5,.3],fe_london:["ExCeL London circuit","London, UK","street",1.45,.0],
 // Supercars
 sydney:["Sydney Motorsport Park","Sydney, Australia","road",2.43,.15],taupo:["Taupo International Motorsport Park","Taupo, New Zealand","road",2.0,.25],symmons:["Symmons Plains Raceway","Launceston, Australia","road",1.5,.25],wanneroo:["Wanneroo Raceway","Perth, Australia","road",1.5,.08],
 hiddenvalley:["Hidden Valley Raceway","Darwin, Australia","road",1.8,.15],townsville:["Reid Park Street Circuit","Townsville, Australia","street",1.8,.1],ipswich:["Queensland Raceway","Ipswich, Australia","road",1.95,.1],sandown:["Sandown Raceway","Melbourne, Australia","road",1.93,.25],
 thebend:["The Bend Motorsport Park","Tailem Bend, Australia","road",2.1,.15],bathurst:["Mount Panorama Circuit","Bathurst, Australia","road",3.86,.3],goldcoast:["Surfers Paradise Street Circuit","Gold Coast, Australia","street",1.84,.2],adelaide:["Adelaide Street Circuit","Adelaide, Australia","street",2.0,.12],
 // Dirt (real)
 knoxville:["Knoxville Raceway","Knoxville, IA","dirt",0.5,.15],eldora:["Eldora Speedway","Rossburg, OH","dirt",0.5,.15],williamsgrove:["Williams Grove Speedway","Mechanicsburg, PA","dirt",0.5,.15],portroyal:["Port Royal Speedway","Port Royal, PA","dirt",0.5,.15],
 lernerville:["Lernerville Speedway","Sarver, PA","dirt",0.41,.15],volusia:["Volusia Speedway Park","Barberville, FL","dirt",0.5,.12],attica:["Attica Raceway Park","Attica, OH","dirt",0.375,.15],skagit:["Skagit Speedway","Alger, WA","dirt",0.375,.2],
 jackson:["Jackson Motorplex","Jackson, MN","dirt",0.5,.15],ohsweken:["Ohsweken Speedway","Ohsweken, ON","dirt",0.375,.15],cedarlake:["Cedar Lake Speedway","New Richmond, WI","dirt",0.375,.15],tulsa:["Tulsa Expo Raceway (Chili Bowl)","Tulsa, OK","dirt",0.25,.0],
 eastbay:["East Bay Raceway Park","Gibsonton, FL","dirt",0.333,.12],florence:["Florence Speedway","Union, KY","dirt",0.5,.15],brownstown:["Brownstown Speedway","Brownstown, IN","dirt",0.25,.15],portsmouth:["Portsmouth Raceway Park","Portsmouth, OH","dirt",0.375,.15],
 atomic:["Atomic Speedway","Chillicothe, OH","dirt",0.375,.15],lincoln:["Lincoln Speedway","Abbottstown, PA","dirt",0.375,.15],bigdiamond:["Big Diamond Speedway","Pottsville, PA","dirt",0.5,.15],
 // NHRA
 gainesville:["Gainesville Raceway","Gainesville, FL","drag",.25,.15],pomona:["Pomona Dragstrip","Pomona, CA","drag",.25,.03],wildhorse:["Wild Horse Pass Motorsports Park","Chandler, AZ","drag",.25,.02],vegasdrag:["The Strip at Las Vegas Motor Speedway","Las Vegas, NV","drag",.25,.02],
 zmax:["zMAX Dragway","Concord, NC","drag",.25,.15],route66:["Route 66 Raceway","Joliet, IL","drag",.25,.15],bristoldrag:["Bristol Dragway","Bristol, TN","drag",.25,.15],summit:["Summit Motorsports Park","Norwalk, OH","drag",.25,.15],
 pacific:["Pacific Raceways","Kent, WA","drag",.25,.2],sonomadrag:["Sonoma Raceway dragstrip","Sonoma, CA","drag",.25,.03],brainerd:["Brainerd International Raceway","Brainerd, MN","drag",.25,.15],indydrag:["Lucas Oil Indianapolis Raceway Park dragstrip","Brownsburg, IN","drag",.25,.15],
 maplegrove:["Maple Grove Raceway","Mohnton, PA","drag",.25,.15],motorplex:["Texas Motorplex","Ennis, TX","drag",.25,.1],wwtdrag:["World Wide Technology Raceway dragstrip","Madison, IL","drag",.25,.12],
 // Karting (real)
 okc:["Orlando Kart Center","Orlando, FL","kart",.8,.12],newcastle:["New Castle Motorsports Park","New Castle, IN","kart",.9,.15],gopro:["GoPro Motorplex","Mooresville, NC","kart",.75,.15],vegaskart:["SuperNationals street circuit","Las Vegas, NV","kart",.6,.02],
 lonato:["South Garda Karting","Lonato, Italy","kart",.75,.15],genk:["Karting Genk","Genk, Belgium","kart",.82,.3],zuera:["Circuito Internacional de Zuera","Zuera, Spain","kart",.8,.05],kristianstad:["Asum Ring","Kristianstad, Sweden","kart",.75,.3],franciacorta:["Franciacorta Karting Track","Castrezzato, Italy","kart",.8,.15],
 // Fictional local venues (grassroots)
 f_cedar:["Cedar Ridge Speedway (3/8-mile asphalt)","your home county","sht",.375,.15],f_thunder:["Thunder Valley Raceway (1/2-mile asphalt)","the next county over","sht",.5,.15],f_river:["Riverbend Motor Speedway (1/4-mile)","down by the river","sht",.25,.15],
 f_pine:["Pine Hollow Speedway (4/10-mile)","two hours north","sht",.4,.15],f_lake:["Lakeview Motor Speedway (1/3-mile)","the lake country","sht",.333,.15],f_iron:["Iron Hill Speedway (5/8-mile)","the state capital","sht",.625,.15],
 f_clay:["Red Clay Raceway (dirt)","your home county","dirt",.25,.15],f_copper:["Copper Basin Speedway (dirt)","out past the quarry","dirt",.333,.15],f_prairie:["Prairie Wind Dirt Track","the county fairgrounds","dirt",.375,.15],
 f_hollister:["Hollister Clay Oval","three hours west","dirt",.5,.15],f_gravel:["Gravel Creek Raceway","the state line","dirt",.25,.15],f_mesa:["Mesa Bend Mini Oval (dirt)","the edge of town","dirt",.125,.15],
 f_lakeside:["Lakeside Kart Club","your hometown","kart",.6,.15],f_tri:["Tri-County Kart Park","the next town over","kart",.7,.15],f_valley:["Valley View Karting","two hours south","kart",.65,.15],f_ridge:["Ridgeline Kartplex","across the state","kart",.8,.15],f_summit:["Summit Point Kart Center","the mountains","kart",.75,.15]
};
const TTYPE_N={ss:"Superspeedway",int:"Intermediate oval",sht:"Short track",dirt:"Dirt oval",road:"Road course",street:"Street circuit",kart:"Kart circuit",drag:"Drag strip"};
function tkn(id){return TRK[id]?TRK[id][0]:id;}
function tkt(id){return TRK[id]?TRK[id][2]:"road";}
