/* ===================== REAL TEAMS & DRIVERS (2025-26 snapshot) ===================== */
// Real names appear inside a fictional story. Ratings are game estimates, not real-world judgments.
// [team, manufacturer/engine, car quality, owner/principal, [[car #, driver, nationality, birth year, rating, traits(o=oval r=road d=dirt w=wet), co-drivers...]]]
const REAL={
 cup:[["Hendrick Motorsports","Chevrolet",93,"Rick Hendrick",[[5,"Kyle Larson","USA",1992,92,"d8r1"],[9,"Chase Elliott","USA",1995,88,"r3"],[24,"William Byron","USA",1997,89,""],[48,"Alex Bowman","USA",1993,82,""]]],
  ["Joe Gibbs Racing","Toyota",92,"Joe Gibbs",[[11,"Denny Hamlin","USA",1980,90,"o2"],[19,"Chase Briscoe","USA",1994,85,"d5"],[20,"Christopher Bell","USA",1994,89,"d8"],[54,"Ty Gibbs","USA",2002,82,"r2"]]],
  ["Team Penske","Ford",89,"Roger Penske",[[2,"Austin Cindric","USA",1998,80,"r3"],[12,"Ryan Blaney","USA",1993,89,""],[22,"Joey Logano","USA",1990,88,""]]],
  ["Wood Brothers Racing","Ford",80,"Eddie and Len Wood",[[21,"Josh Berry","USA",1990,80,""]]],
  ["23XI Racing","Toyota",88,"Michael Jordan and Denny Hamlin",[[23,"Bubba Wallace","USA",1993,83,""],[45,"Tyler Reddick","USA",1996,87,"d5r2"],[35,"Riley Herbst","USA",1999,76,""]]],
  ["Trackhouse Racing","Chevrolet",83,"Justin Marks",[[1,"Ross Chastain","USA",1992,84,""],[88,"Connor Zilisch","USA",2006,80,"r6"],[97,"Shane van Gisbergen","NZL",1989,84,"r10o-4w5"]]],
  ["RFK Racing","Ford",83,"Brad Keselowski",[[6,"Brad Keselowski","USA",1984,81,""],[17,"Chris Buescher","USA",1992,84,""],[60,"Ryan Preece","USA",1990,80,""]]],
  ["Richard Childress Racing","Chevrolet",80,"Richard Childress",[[3,"Austin Dillon","USA",1990,77,""],[33,"Austin Hill","USA",1994,79,""]]],
  ["Legacy Motor Club","Toyota",79,"Jimmie Johnson",[[42,"John Hunter Nemechek","USA",1997,79,""],[43,"Erik Jones","USA",1996,79,""]]],
  ["Spire Motorsports","Chevrolet",79,"Jeff Dickerson and T.J. Puchyr",[[7,"Daniel Suárez","MEX",1992,80,"r3"],[71,"Michael McDowell","USA",1984,79,"r5"],[77,"Carson Hocevar","USA",2003,81,""]]],
  ["Kaulig Racing","Chevrolet",76,"Matt Kaulig",[[10,"Ty Dillon","USA",1992,74,""],[16,"AJ Allmendinger","USA",1981,79,"r7"]]],
  ["Front Row Motorsports","Ford",77,"Bob Jenkins",[[4,"Noah Gragson","USA",1998,76,""],[34,"Todd Gilliland","USA",2000,76,""],[38,"Zane Smith","USA",1999,78,""]]],
  ["Haas Factory Team","Chevrolet",74,"Gene Haas",[[41,"Cole Custer","USA",1998,77,""]]],
  ["Hyak Motorsports","Chevrolet",74,"Hyak Motorsports ownership group",[[47,"Ricky Stenhouse Jr.","USA",1987,77,"d3"]]],
  ["Rick Ware Racing","Chevrolet",68,"Rick Ware",[[51,"Cody Ware","USA",1995,68,""]]]],
 oap:[["JR Motorsports","Chevrolet",88,"Dale Earnhardt Jr.",[[1,"Carson Kvapil","USA",2003,79,""],[7,"Justin Allgaier","USA",1986,82,""],[8,"Sammy Smith","USA",2004,77,""],[88,"Rajah Caruth","USA",2002,75,""]]],
  ["Haas Factory Team","Chevrolet",84,"Gene Haas",[["00","Sheldon Creed","USA",1997,80,"r2"],[41,"Sam Mayer","USA",2003,79,"r2"]]],
  ["Richard Childress Racing","Chevrolet",84,"Richard Childress",[[2,"Jesse Love","USA",2005,79,""],[21,null]]],
  ["Joe Gibbs Racing","Toyota",86,"Joe Gibbs",[[18,"William Sawalich","USA",2006,76,""],[19,"Brent Crews","USA",2008,74,""],[20,"Brandon Jones","USA",1997,78,""],[54,"Taylor Gray","USA",2005,77,""]]],
  ["Hendrick Motorsports","Chevrolet",85,"Rick Hendrick",[[17,"Corey Day","USA",2005,77,"d8"]]],
  ["Viking Motorsports","Chevrolet",76,"Viking Motorsports ownership",[[96,"Anthony Alfredo","USA",1999,72,""],[99,"Parker Retzlaff","USA",2003,74,""]]],
  ["RSS Racing","Ford",72,"Rod Sieg",[[39,"Ryan Sieg","USA",1993,74,""],[28,"Kyle Sieg","USA",1996,69,""]]],
  ["Alpha Prime Racing","Chevrolet",70,"Tommy Joe Martins",[[44,"Brennan Poole","USA",1991,71,""],[45,"Lavar Scott","USA",2002,69,""]]],
  ["Sam Hunt Racing","Toyota",74,"Sam Hunt",[[24,"Harrison Burton","USA",2000,74,""],[26,"Dean Thompson","USA",2002,70,""]]],
  ["Jeremy Clements Racing","Chevrolet",66,"Tony Clements",[[51,"Jeremy Clements","USA",1985,68,""]]],
  ["Jordan Anderson Racing","Chevrolet",70,"Jordan Anderson",[[27,"Jeb Burton","USA",1992,70,""],[31,"Blaine Perkins","USA",2002,67,""]]],
  ["Big Machine Racing","Chevrolet",70,"Scott Borchetta",[[48,"Patrick Staropoli","USA",1997,68,""]]],
  ["SS-Greenlight Racing","Chevrolet",64,"Bobby Dotter",[["07","Josh Bilicki","USA",1995,66,"r4"],[14,"Garrett Smithley","USA",1992,64,""]]],
  ["Young's Motorsports","Chevrolet",64,"Tyler Young",[["02","Ryan Ellis","USA",1989,66,"r3"]]],
  ["Peterson Racing","Chevrolet",66,"Peterson Racing ownership",[[87,"Austin Green","USA",1997,66,""]]],
  ["DGM Racing","Chevrolet",63,"Mario Gosselin",[[92,"Josh Williams","USA",1993,66,""],[91,"Mason Maggio","USA",2000,62,""]]],
  ["Joey Gase Motorsports","Chevrolet",60,"Joey Gase",[[35,"Joey Gase","USA",1993,62,""]]]],
 truck:[["TRICON Garage","Toyota",86,"David Gilliland",[[1,"Corey Heim","USA",2002,82,""],[11,"Kaden Honeycutt","USA",2003,75,""],[15,"Tanner Gray","USA",1999,73,""],[17,"Gio Ruggiero","USA",2006,74,""],[5,"Nick Leitz","USA",2003,67,""]]],
  ["Front Row Motorsports","Ford",84,"Bob Jenkins",[[34,"Layne Riggs","USA",2002,78,""],[38,"Chandler Smith","USA",2002,79,""]]],
  ["ThorSport Racing","Ford",80,"Duke and Rhonda Thorson",[[13,"Cole Butcher","CAN",1998,72,""],[88,"Ty Majeski","USA",1994,79,""],[98,"Jake Garcia","USA",2005,72,""],[99,"Ben Rhodes","USA",1997,75,""]]],
  ["McAnally-Hilgemann Racing","Chevrolet",80,"Bill McAnally",[[18,"Tyler Ankrum","USA",2001,74,""],[19,"Daniel Hemric","USA",1991,77,""],[81,"Kris Wright","USA",1999,66,""],[91,"Christian Eckes","USA",2001,78,""]]],
  ["Kaulig Racing","Ram",78,"Matt Kaulig",[[10,"Daniel Dye","USA",2003,71,""],[12,"Brenden Queen","USA",2001,72,""],[14,"Mini Tyrrell","GBR",2007,66,"r3"],[16,"Justin Haley","USA",1999,75,""]]],
  ["Spire Motorsports","Chevrolet",82,"Jeff Dickerson and T.J. Puchyr",[[7,"Connor Mosack","USA",1998,70,"r2"],[77,null]]],
  ["Niece Motorsports","Chevrolet",74,"Al Niece",[[44,"Andrés Pérez de Lara","MEX",2004,70,""],[42,"Tyler Reif","USA",2003,66,""]]],
  ["Halmar Friesen Racing","Toyota",74,"Stewart Friesen",[[52,"Stewart Friesen","CAN",1983,72,"d10"]]],
  ["CR7 Motorsports","Chevrolet",72,"Codie Rohrbaugh",[[9,"Grant Enfinger","USA",1985,75,""]]],
  ["Rackley W.A.R.","Chevrolet",68,"Curtis Rackley",[[26,"Dawson Sutton","USA",2006,66,""]]],
  ["Freedom Racing Enterprises","Chevrolet",62,"Freedom Racing ownership",[[76,"Spencer Boyd","USA",1995,63,""]]],
  ["Team Reaume","Ford",60,"Josh Reaume",[[22,"Josh Reaume","CAN",1991,60,""],[33,"Frankie Muniz","USA",1985,58,""]]]],
 arca:[["Venturini Motorsports","Toyota",80,"Billy Venturini",[[15,null],[20,null],[25,null],[55,null]]],["Joe Gibbs Racing","Toyota",84,"Joe Gibbs",[[18,null]]],["Rette Jones Racing","Ford",72,"Mark Rette",[[30,null]]],
  ["Pinnacle Racing Group","Chevrolet",76,"Pinnacle Racing Group",[[28,null]]],["Nitro Motorsports","Toyota",72,"Nitro Motorsports",[[70,null]]],["Bill McAnally Racing","Chevrolet",74,"Bill McAnally",[[16,null],[19,null]]],
  ["Fast Track Racing","Ford",58,"Andy Hillenburg",[[10,null],[11,null],[12,null]]],["Clubb Racing","Ford",56,"Brad Clubb",[[86,null]]],["Greg Van Alst Motorsports","Ford",64,"Greg Van Alst",[[35,null]]],["Cook Racing Technologies","Chevrolet",66,"Cook Racing",[[17,null]]]],
 indycar:[["Team Penske","Chevrolet",91,"Roger Penske",[[2,"Josef Newgarden","USA",1990,88,"o4"],[3,"Scott McLaughlin","NZL",1993,88,""],[12,"David Malukas","USA",2001,83,"o3"]]],
  ["Chip Ganassi Racing","Honda",93,"Chip Ganassi",[[10,"Álex Palou","ESP",1997,95,""],[9,"Scott Dixon","NZL",1980,90,"w4"],[8,"Kyffin Simpson","CAY",2004,76,""]]],
  ["Arrow McLaren","Chevrolet",88,"Zak Brown",[[5,"Pato O'Ward","MEX",1999,89,"o3"],[7,"Christian Lundgaard","DEN",2001,85,"r3"],[6,"Nolan Siegel","USA",2004,77,""]]],
  ["Andretti Global","Honda",86,"Dan Towriss",[[26,"Will Power","AUS",1981,87,"r3"],[27,"Kyle Kirkwood","USA",1998,86,"r3"],[28,"Marcus Ericsson","SWE",1990,83,"o2"]]],
  ["Rahal Letterman Lanigan Racing","Honda",80,"Bobby Rahal",[[15,"Graham Rahal","USA",1989,80,""],[45,"Louis Foster","GBR",2003,78,""],[47,"Mick Schumacher","GER",1999,79,"r2"]]],
  ["Meyer Shank Racing","Honda",82,"Mike Shank",[[60,"Felix Rosenqvist","SWE",1991,84,""],[66,"Marcus Armstrong","NZL",2000,82,""]]],
  ["A.J. Foyt Racing","Chevrolet",78,"Larry Foyt",[[14,"Santino Ferrucci","USA",1998,80,"o5"],[4,"Caio Collet","BRA",2002,77,""]]],
  ["Ed Carpenter Racing","Chevrolet",79,"Ed Carpenter",[[20,"Alexander Rossi","USA",1991,84,"o2"],[21,"Christian Rasmussen","DEN",2000,79,""]]],
  ["Dale Coyne Racing","Honda",74,"Dale Coyne",[[18,"Romain Grosjean","FRA",1986,80,"r3"],[19,"Dennis Hauger","NOR",2003,79,""]]],
  ["Juncos Hollinger Racing","Chevrolet",74,"Ricardo Juncos",[[76,"Rinus VeeKay","NED",2000,79,""],[77,"Sting Ray Robb","USA",2001,71,""]]]],
 nxt:[["Andretti Global","Dallara-HMD",80,"Dan Towriss",[[26,null],[27,null],[28,null]]],["HMD Motorsports","Dallara-HMD",80,"Henry Malukas",[[1,null],[11,null],[39,null],[71,null]]],["Abel Motorsports","Dallara-HMD",72,"Abel Motorsports",[[51,null],[19,null]]],
  ["Cape Motorsports","Dallara-HMD",70,"Dan Andersen",[[2,null],[3,null]]],["Chip Ganassi Racing","Dallara-HMD",78,"Chip Ganassi",[[9,null],[10,null]]],["Juncos Hollinger Racing","Dallara-HMD",70,"Ricardo Juncos",[[76,null],[77,null]]],["Cusick Motorsports","Dallara-HMD",64,"Cusick Motorsports",[[23,null]]]],
 f1:[["McLaren F1 Team","Mercedes",95,"Zak Brown",[[1,"Lando Norris","GBR",1999,94,"w3"],[81,"Oscar Piastri","AUS",2001,93,""]]],
  ["Mercedes-AMG Petronas F1 Team","Mercedes",93,"Toto Wolff",[[63,"George Russell","GBR",1998,93,"w2"],[12,"Kimi Antonelli","ITA",2006,86,""]]],
  ["Oracle Red Bull Racing","Red Bull Ford",90,"Laurent Mekies",[[3,"Max Verstappen","NED",1997,97,"w6"],[6,"Isack Hadjar","FRA",2004,84,""]]],
  ["Scuderia Ferrari HP","Ferrari",91,"Fred Vasseur",[[16,"Charles Leclerc","MON",1997,92,""],[44,"Lewis Hamilton","GBR",1985,89,"w5"]]],
  ["Atlassian Williams Racing","Mercedes",84,"James Vowles",[[23,"Alex Albon","THA",1996,87,""],[55,"Carlos Sainz","ESP",1994,89,""]]],
  ["Visa Cash App Racing Bulls","Red Bull Ford",80,"Alan Permane",[[30,"Liam Lawson","NZL",2002,82,""],[41,"Arvid Lindblad","GBR",2007,80,""]]],
  ["Aston Martin Aramco F1 Team","Honda",82,"Lawrence Stroll",[[14,"Fernando Alonso","ESP",1981,89,"w4"],[18,"Lance Stroll","CAN",1998,80,"w3"]]],
  ["MoneyGram Haas F1 Team","Ferrari",79,"Ayao Komatsu",[[31,"Esteban Ocon","FRA",1996,84,""],[87,"Oliver Bearman","GBR",2005,84,""]]],
  ["Audi Revolut F1 Team","Audi",77,"Jonathan Wheatley",[[27,"Nico Hülkenberg","GER",1987,85,"w2"],[5,"Gabriel Bortoleto","BRA",2004,83,""]]],
  ["BWT Alpine F1 Team","Mercedes",80,"Flavio Briatore",[[10,"Pierre Gasly","FRA",1996,86,"w2"],[43,"Franco Colapinto","ARG",2003,80,""]]],
  ["Cadillac Formula 1 Team","Ferrari",72,"Graeme Lowdon",[[11,"Sergio Pérez","MEX",1990,85,""],[77,"Valtteri Bottas","FIN",1989,85,""]]]],
 f2:[["Campos Racing","Mecachrome",72,"Adrián Campos Jr.",[[1,"Nikola Tsolov","BUL",2007,78,""],[2,null]]],["Invicta Racing","Mecachrome",74,"Invicta Racing",[[3,"Rafael Câmara","BRA",2005,79,""],[4,null]]],
  ["Hitech TGR","Mecachrome",73,"Oliver Oakes",[[5,"Colton Herta","USA",2000,82,""],[6,"Dino Beganovic","SWE",2004,77,""]]],["MP Motorsport","Mecachrome",72,"Sander Dorsman",[[7,"Gabriele Minì","ITA",2005,77,""],[8,"Oliver Goethe","GER",2004,74,""]]],
  ["Rodin Motorsport","Mecachrome",71,"Rodin Motorsport",[[9,"Alex Dunne","IRL",2005,78,""],[10,"Martinius Stenshorne","NOR",2005,76,""]]],["ART Grand Prix","Mecachrome",72,"Sébastien Philippe",[[11,"Tim Tramnitz","GER",2004,74,""],[12,null]]],
  ["PREMA Racing","Mecachrome",71,"René Rosin",[[14,"Sebastián Montoya","COL",2005,75,""],[15,"Mari Boya","ESP",2005,73,""]]],["DAMS Lucas Oil","Mecachrome",69,"Charles Pic",[[16,"Kush Maini","IND",2000,75,""],[17,null]]],
  ["Trident","Mecachrome",68,"Giacomo Ricci",[[20,"Laurens van Hoepen","NED",2005,74,""],[21,"John Bennett","GBR",2003,72,""]]],["AIX Racing","Mecachrome",66,"AIX Racing",[[22,"Joshua Dürksen","PAR",2003,75,""],[23,null]]],
  ["Van Amersfoort Racing","Mecachrome",67,"Frits van Amersfoort",[[24,"Ritomo Miyata","JPN",1999,74,""],[25,"Roman Staněk","CZE",2004,74,""]]]],
 f3:[["PREMA Racing","Mecachrome",72,"René Rosin",[[1,null],[2,"Ugo Ugochukwu","USA",2007,73,""],[3,null]]],["Trident","Mecachrome",72,"Giacomo Ricci",[[4,"Noah Strømsted","DEN",2006,72,""],[5,null],[6,null]]],
  ["ART Grand Prix","Mecachrome",71,"Sébastien Philippe",[[7,"Tuukka Taponen","FIN",2006,72,""],[8,null],[9,null]]],["Hitech TGR","Mecachrome",70,"Oliver Oakes",[[10,"Freddie Slater","GBR",2008,73,""],[11,null],[12,null]]],
  ["MP Motorsport","Mecachrome",71,"Sander Dorsman",[[14,"Charlie Wurz","AUT",2005,71,""],[15,null],[16,null]]],["Campos Racing","Mecachrome",68,"Adrián Campos Jr.",[[17,"Roman Bilinski","GBR",2004,71,""],[18,null],[19,null]]],
  ["Van Amersfoort Racing","Mecachrome",67,"Frits van Amersfoort",[[20,"Théophile Naël","FRA",2004,70,""],[21,null],[22,null]]],["Rodin Motorsport","Mecachrome",67,"Rodin Motorsport",[[23,"Callum Voisin","GBR",2005,70,""],[24,null],[25,null]]],
  ["AIX Racing","Mecachrome",64,"AIX Racing",[[26,null],[27,null],[28,null]]],["DAMS Lucas Oil","Mecachrome",65,"Charles Pic",[[29,"Alessandro Giusti","FRA",2006,70,""],[30,null],[31,null]]]],
 freca:[["PREMA Racing","Alpine",70,"René Rosin",[[1,null],[2,null],[3,null]]],["R-ace GP","Alpine",70,"R-ace GP",[[4,null],[5,null],[6,null]]],["ART Grand Prix","Alpine",68,"Sébastien Philippe",[[7,null],[8,null],[9,null]]],["MP Motorsport","Alpine",68,"Sander Dorsman",[[10,null],[11,null],[12,null]]],
  ["Van Amersfoort Racing","Alpine",66,"Frits van Amersfoort",[[14,null],[15,null],[16,null]]],["KIC Motorsport","Alpine",62,"KIC Motorsport",[[17,null],[18,null]]],["Trident","Alpine",65,"Giacomo Ricci",[[19,null],[20,null],[21,null]]],["RPM","Alpine",60,"RPM",[[22,null],[23,null]]]],
 imsagtp:[["Porsche Penske Motorsport","Porsche 963",88,"Roger Penske",[[6,"Kévin Estre","FRA",1988,88,"w3","Laurens Vanthoor"],[7,"Felipe Nasr","BRA",1992,86,"","Julien Andlauer"]]],
  ["Cadillac Wayne Taylor Racing","Cadillac V-Series.R",85,"Wayne Taylor",[[10,"Ricky Taylor","USA",1989,84,"","Filipe Albuquerque"],[40,"Jordan Taylor","USA",1991,85,"","Louis Delétraz"]]],
  ["Cadillac Whelen","Cadillac V-Series.R",83,"Action Express Racing",[[31,"Jack Aitken","GBR",1995,84,"","Frederik Vesti"]]],
  ["Acura Meyer Shank Racing","Acura ARX-06",84,"Mike Shank",[[60,"Tom Blomqvist","GBR",1993,85,"","Colin Braun"],[93,"Renger van der Zande","NED",1986,83,"","Nick Yelloly"]]],
  ["BMW M Team RLL","BMW M Hybrid V8",84,"Bobby Rahal",[[24,"Sheldon van der Linde","RSA",1999,84,"","Robin Frijns"],[25,"Philipp Eng","AUT",1990,83,"","Marco Wittmann"]]],
  ["Aston Martin THOR Team (IMSA)","Aston Martin Valkyrie",80,"Heart of Racing",[[23,"Ross Gunn","GBR",1997,82,"","Roman De Angelis"]]]],
 wec:[["Ferrari AF Corse","Ferrari 499P",90,"Antonello Coletta",[[50,"Antonio Fuoco","ITA",1996,87,"","Miguel Molina","Nicklas Nielsen"],[51,"Alessandro Pier Guidi","ITA",1983,87,"","James Calado","Antonio Giovinazzi"]]],
  ["Toyota Gazoo Racing","Toyota TR010",88,"Kazuki Nakajima",[[7,"Kamui Kobayashi","JPN",1986,85,"","Mike Conway"],[8,"Brendon Hartley","NZL",1989,87,"","Ryo Hirakawa"]]],
  ["Cadillac Hertz Team JOTA","Cadillac V-Series.R",85,"Sam Hignett",[[12,"Alex Lynn","GBR",1993,85,"","Will Stevens"],[38,"Earl Bamber","NZL",1990,85,"","Sébastien Bourdais"]]],
  ["BMW M Team WRT","BMW M Hybrid V8",84,"Vincent Vosse",[[15,"Kevin Magnussen","DEN",1992,85,"","Dries Vanthoor","Raffaele Marciello"],[20,"René Rast","GER",1986,85,""]]],
  ["Alpine Endurance Team","Alpine A424",82,"Alpine",[[35,"Paul-Loup Chatin","FRA",1991,82,"","Ferdinand Habsburg","Charles Milesi"],[36,"Jules Gounon","FRA",1994,83,"","Frédéric Makowiecki"]]],
  ["Peugeot TotalEnergies","Peugeot 9X8",81,"Peugeot Sport",[[93,"Paul di Resta","GBR",1986,82,"","Mikkel Jensen"],[94,"Stoffel Vandoorne","BEL",1992,85,"","Loïc Duval","Malthe Jakobsen"]]],
  ["Aston Martin THOR Team","Aston Martin Valkyrie",80,"Heart of Racing",[["007","Harry Tincknell","GBR",1991,82,"","Tom Gamble"],["009","Alex Riberas","ESP",1993,82,"","Marco Sørensen"]]],
  ["Genesis Magma Racing","Genesis GMR-001",78,"Genesis Magma Racing",[[17,"André Lotterer","GER",1981,83,""]]]],
 imsagtd:[["Paul Miller Racing","BMW M4 GT3",72,"Paul Miller",[[1,null]]],["Wright Motorsports","Porsche 911 GT3 R",72,"John Wright",[[120,null]]],["Vasser Sullivan","Lexus RC F GT3",72,"Jimmy Vasser",[[12,null],[14,null]]],["Heart of Racing Team","Aston Martin Vantage GT3",72,"Heart of Racing",[[27,null]]],
  ["Turner Motorsport","BMW M4 GT3",70,"Will Turner",[[96,null]]],["AO Racing","Porsche 911 GT3 R",72,"Anders Ottesen",[[77,null]]],["Winward Racing","Mercedes-AMG GT3",73,"Winward Racing",[[57,null]]],["Korthoff Competition Motors","Mercedes-AMG GT3",68,"Korthoff",[[32,null]]],
  ["Pfaff Motorsports","Lamborghini Huracán GT3",70,"Chris Pfaff",[[9,null]]],["Inception Racing","Ferrari 296 GT3",66,"Inception Racing",[[70,null]]],["Gradient Racing","Ford Mustang GT3",66,"Gradient Racing",[[66,null]]],["Conquest Racing","Ferrari 296 GT3",66,"Conquest Racing",[[34,null]]],["Triarsi Competizione","Ferrari 296 GT3",66,"Triarsi",[[21,null]]]],
 wecgt:[["Manthey","Porsche 911 GT3 R",73,"Manthey",[[91,null],[92,null]]],["Iron Lynx","Lamborghini Huracán GT3",68,"Iron Lynx",[[60,null]]],["TF Sport","Corvette Z06 GT3.R",72,"Tom Ferrier",[[33,null],[81,null]]],["United Autosports","McLaren 720S GT3",70,"Zak Brown and Richard Dean",[[59,null],[95,null]]],
  ["Vista AF Corse","Ferrari 296 GT3",72,"AF Corse",[[21,null],[54,null]]],["Team WRT","BMW M4 GT3",72,"Vincent Vosse",[[31,null],[46,null]]],["Proton Competition","Ford Mustang GT3",68,"Christian Ried",[[77,null],[88,null]]],["Akkodis ASP","Lexus RC F GT3",68,"Akkodis ASP",[[78,null],[87,null]]],["Heart of Racing Team","Aston Martin Vantage GT3",70,"Heart of Racing",[[27,null]]]],
 fe:[["TAG Heuer Porsche Formula E Team","Porsche",91,"Florian Modlinger",[[94,"Pascal Wehrlein","GER",1994,89,""],[51,"Nico Müller","SUI",1992,83,""]]],
  ["Jaguar TCS Racing","Jaguar",90,"James Barclay",[[9,"Mitch Evans","NZL",1994,88,""],[13,"António Félix da Costa","POR",1991,86,""]]],
  ["Nissan Formula E Team","Nissan",88,"Tommaso Volpe",[[23,"Oliver Rowland","GBR",1992,89,""],[17,"Norman Nato","FRA",1992,80,""]]],
  ["DS Penske","DS",82,"Jay Penske",[[7,"Maximilian Günther","GER",1997,84,""],[77,"Taylor Barnard","GBR",2004,82,""]]],
  ["Andretti Formula E","Porsche",84,"Roger Griffiths",[[1,"Jake Dennis","GBR",1995,85,""],[28,"Felipe Drugovich","BRA",2000,80,""]]],
  ["Mahindra Racing","Mahindra",83,"Frédéric Bertrand",[[48,"Edoardo Mortara","SUI",1987,84,""],[21,"Nyck de Vries","NED",1995,84,""]]],
  ["Envision Racing","Jaguar",82,"Sylvain Filippi",[[16,"Sébastien Buemi","SUI",1988,84,""],[18,"Joel Eriksson","SWE",1998,79,""]]],
  ["Citroën Racing","Stellantis",84,"Citroën Racing",[[25,"Jean-Éric Vergne","FRA",1990,86,""],[37,"Nick Cassidy","NZL",1994,86,""]]],
  ["Lola Yamaha ABT","Lola-Yamaha",76,"Thomas Biermaier",[[11,"Lucas di Grassi","BRA",1984,82,""],[22,"Zane Maloney","BRB",2003,78,""]]],
  ["Cupra Kiro","Porsche",77,"Kiro Race Co",[[33,"Dan Ticktum","GBR",1999,83,""],[3,"Pepe Martí","ESP",2005,78,""]]]],
 woo:[["Big Game Motorsports","Sprint car",86,"Chris Dyson",[[2,"David Gravel","USA",1992,89,""]]],["Jason Johnson Racing","Sprint car",84,"Jason Johnson Racing",[[41,"Carson Macedo","USA",1996,87,""]]],
  ["Stenhouse Jr./Marshall Racing","Sprint car",82,"Ricky Stenhouse Jr. and Tod Quiring",[[17,"Sheldon Haudenschild","USA",1994,86,""]]],["Tony Stewart Racing","Sprint car",82,"Tony Stewart",[[15,"Donny Schatz","USA",1977,84,""],[14,"Zeb Wise","USA",2002,81,""]]],
  ["Shark Racing","Sprint car",80,"Jac Haudenschild",[["1S","Logan Schuchart","USA",1994,83,""]]],["Kasey Kahne Racing","Sprint car",82,"Kasey Kahne",[[9,"Giovanni Scelzi","USA",2002,84,""],[19,"Spencer Bayston","USA",1999,82,""]]],
  ["Roth Motorsports","Sprint car",80,"Dennis Roth",[[83,"James McFadden","AUS",1992,80,""]]],["Balog Racing","Sprint car",72,"Bill Balog",[["1B","Bill Balog","USA",1977,77,""]]],
  ["Eliason Motorsports","Sprint car",76,"Cory Eliason",[[11,"Cory Eliason","USA",1997,80,""]]],["Madsen Racing","Sprint car",74,"Kerry Madsen",[[29,"Kerry Madsen","AUS",1972,77,""]]],["Timms Racing","Sprint car",78,"Paul Silva",[[24,"Ryan Timms","USA",2006,80,""]]]],
 hlr:[["Brad Sweet Racing","Sprint car",84,"Brad Sweet",[[49,"Brad Sweet","USA",1985,86,""]]],["Rico Abreu Racing","Sprint car",82,"Rico Abreu",[[24,"Rico Abreu","USA",1992,84,""]]],["Courtney Racing","Sprint car",80,"Tyler Courtney",[[7,"Tyler Courtney","USA",1993,82,""]]],
  ["Reutzel Racing","Sprint car",80,"Aaron Reutzel",[[87,"Aaron Reutzel","USA",1989,82,""]]],["Peck Racing","Sprint car",76,"Justin Peck",[[13,"Justin Peck","USA",1987,80,""]]],["Marks Racing","Sprint car",76,"Brent Marks",[[19,"Brent Marks","USA",1997,80,""]]],
  ["Macri Racing","Sprint car",78,"Anthony Macri",[[39,"Anthony Macri","USA",1997,82,""]]],["Dewease Racing","Sprint car",74,"Lance Dewease",[[69,"Lance Dewease","USA",1965,78,""]]]],
 lolmds:[["Davenport Racing","Late model",84,"Jonathan Davenport",[[49,"Jonathan Davenport","USA",1984,89,""]]],["Sheppard Racing","Late model",84,"Brandon Sheppard",[[1,"Brandon Sheppard","USA",1993,88,""]]],["O'Neal Racing","Late model",82,"Hudson O'Neal",[[71,"Hudson O'Neal","USA",1999,87,""]]],
  ["Thornton Racing","Late model",84,"Ricky Thornton Jr.",[[20,"Ricky Thornton Jr.","USA",1990,88,""]]],["Pierce Racing","Late model",80,"Bobby Pierce",[[32,"Bobby Pierce","USA",1997,86,""]]],["Moran Racing","Late model",80,"Devin Moran",[[99,"Devin Moran","USA",1994,85,""]]],
  ["McCreadie Racing","Late model",78,"Tim McCreadie",[[39,"Tim McCreadie","USA",1974,83,""]]],["Erb Racing","Late model",78,"Tyler Erb",[[1,"Tyler Erb","USA",1991,84,""]]],["Marlar Racing","Late model",74,"Mike Marlar",[[157,"Mike Marlar","USA",1978,82,""]]],["English Racing","Late model",74,"Tanner English",[[81,"Tanner English","USA",1993,82,""]]]],
 supercars:[["Triple Eight Race Engineering","Ford",88,"Roland Dane",[[88,"Broc Feeney","AUS",2002,90,""],[87,"Will Brown","AUS",1998,88,""]]],["Walkinshaw Andretti United","Toyota",84,"Ryan Walkinshaw",[[25,"Chaz Mostert","AUS",1992,86,""],[2,"Ryan Wood","NZL",2001,81,""]]],
  ["Dick Johnson Racing","Ford",84,"Dick Johnson",[[17,"Anton De Pasquale","AUS",1995,84,""],[38,"Brodie Kostecki","AUS",1997,85,""]]],["Tickford Racing","Ford",83,"Rod Nash",[[6,"Cam Waters","AUS",1994,87,""],[55,"Thomas Randle","AUS",1995,82,""]]],
  ["Grove Racing","Ford",83,"Stephen Grove",[[19,"Matt Payne","NZL",2002,84,""],[26,"David Reynolds","AUS",1985,81,""]]],["Team 18","Chevrolet",78,"Charlie Schwerkolt",[[18,"Mark Winterbottom","AUS",1981,80,""]]],
  ["Brad Jones Racing","Toyota",78,"Brad Jones",[[8,"Andre Heimgartner","NZL",1995,81,""],[96,"Macauley Jones","AUS",1995,76,""]]],["Erebus Motorsport","Chevrolet",79,"Betty Klimenko",[[9,"Cooper Murray","AUS",2002,78,""]]],
  ["Matt Stone Racing","Chevrolet",74,"Matt Stone",[[4,"Nick Percat","AUS",1988,77,""]]],["PremiAir Racing","Chevrolet",76,"Peter Xiberras",[[31,"James Golding","AUS",1996,77,""],[62,"Richie Stanaway","NZL",1991,77,""]]],["Blanchard Racing Team","Ford",74,"Tim Blanchard",[[3,"Aaron Cameron","AUS",2002,76,""]]]],
 nhra:[["Antron Brown Motorsports","Top Fuel",86,"Antron Brown",[[1,"Antron Brown","USA",1976,89,""]]],["Kalitta Motorsports","Top Fuel",86,"Connie Kalitta",[[2,"Doug Kalitta","USA",1964,86,""],[3,"Shawn Langdon","USA",1982,86,""]]],
  ["John Force Racing","Top Fuel",86,"John Force Racing",[[4,"Brittany Force","USA",1986,88,""]]],["Phillips Racing","Top Fuel",82,"Phillips Racing",[[5,"Justin Ashley","USA",1995,87,""]]],["Capco Contractors","Top Fuel",84,"Torrence family",[[6,"Steve Torrence","USA",1983,85,""]]],
  ["Elite Motorsports","Top Fuel",80,"Richard Freeman",[[7,"Tony Stewart","USA",1971,82,""]]],["Clay Millican Racing","Top Fuel",76,"Clay Millican",[[8,"Clay Millican","USA",1966,80,""]]],["Josh Hart Racing","Top Fuel",78,"Josh Hart",[[9,"Josh Hart","USA",1981,82,""]]],
  ["Scrappers Racing","Top Fuel",72,"Scrappers Racing",[[10,"Jasmine Salinas","USA",1994,76,""]]],["Zetterström Racing","Top Fuel",70,"Ida Zetterström",[[11,"Ida Zetterström","SWE",1997,76,""]]]]
};
// Extra one-off entries for the Indianapolis 500 (real, part-time)
const INDY500_EXTRA=[["Hélio Castroneves","BRA",1975,82,"Meyer Shank Racing",6],["Takuma Sato","JPN",1977,81,"Rahal Letterman Lanigan Racing",75],["Ryan Hunter-Reay","USA",1980,79,"Arrow McLaren",31],["Conor Daly","USA",1991,78,"Dreyer & Reinbold Racing",23],["Ed Carpenter","USA",1981,78,"Ed Carpenter Racing",33],["Katherine Legge","GBR",1980,74,"HMD Motorsports with A.J. Foyt Racing",11],["Jack Harvey","GBR",1993,76,"Dreyer & Reinbold Racing",24],["Jacob Abel","USA",2001,74,"Abel Motorsports",51]];
/* ===================== FICTIONAL NAME POOLS ===================== */
const FN={USA:["Jake","Tyler","Cody","Mason","Logan","Brady","Colt","Hunter","Austin","Wyatt","Cole","Trey","Dalton","Kyle","Ryan","Brandon","Chase","Jesse","Bobby","Ricky","Dustin","Travis","Caleb","Garrett","Landon","Bryce","Dillon","Kaden","Ethan","Nolan","Jordan","Kayla","Hailey","Madison","Brooke","Savannah","Taylor","Morgan","Riley","Emma","Ava","Sierra","Danica","Lexi","Sam","Maddie","Toby","Owen","Gage","Reid"],
 GBR:["Oliver","Harry","George","Jack","Charlie","Alfie","Freddie","Archie","Lewis","Callum","Jamie","Ellis","Olly","Toby","Rory","Isla","Ella","Abbie","Zak","Finley"],AUS:["Liam","Jye","Cooper","Brodie","Jaxon","Lachlan","Kai","Mitchell","Tom","Zane","Josh","Chloe","Riley","Hayden"],
 ITA:["Lorenzo","Matteo","Leonardo","Gabriele","Andrea","Marco","Luca","Alessio","Tommaso","Nicola","Giulia","Federico"],FRA:["Théo","Hugo","Louis","Arthur","Victor","Jules","Sacha","Enzo","Maxime","Paul","Léa","Raphaël"],GER:["Lukas","Felix","Jonas","Leon","Max","Finn","Tim","Niklas","Moritz","Paul","Lena","Ben"],
 ESP:["Pablo","Javier","Álvaro","Iker","Marc","Sergio","Pol","Alex","Daniel","Lucía"],NED:["Daan","Thijs","Bram","Sem","Lars","Jesse","Ruben","Niels","Tim","Fenna"],BRA:["Pedro","Gabriel","Rafael","Enzo","Lucas","Caio","Felipe","Bruno","Thiago","Matheus"],
 MEX:["Diego","Santiago","Emiliano","Alejandro","Sebastián","Rodrigo","Mateo"],JPN:["Haruto","Ren","Sota","Yuki","Kaito","Riku","Hiroto","Daiki"],SCA:["Oskar","Elias","Emil","William","Noah","Magnus","Viktor","Anton","Mikkel","Isak"],
 CAN:["Liam","Alexis","Mathis","Jacob","Owen","Félix","Logan","Zachary"],NZL:["Hayden","Liam","Marcus","Kiri","Josh","Cam"]};
const LN={USA:["Miller","Johnson","Carter","Hayes","Brooks","Dalton","Mercer","Whitfield","Harlan","Turner","Pruitt","Sizemore","Gentry","Crowder","Boone","Rutledge","McCall","Tillman","Haskins","Wade","Coker","Stroud","Pickett","Lyle","Barnes","Tatum","Kessler","Dunlap","Greer","Baxter","Holloway","Sutter","Kramer","Petty","Yates","Rowe","Fenton","Vance","Hollis","Cobb","Ledford","Ingram","Sharpe","Duvall","Raines","Combs","Mabry","Pruett","Lambert","Rhodes","Osborne","Bledsoe","Garner","Crane","Mackey"],
 GBR:["Hughes","Barrett","Fletcher","Whitmore","Ashby","Pemberton","Rowntree","Cartwright","Lockhart","Thornton","Hale","Marsh","Crawley","Stanton","Holt"],AUS:["McKenzie","Dawson","Sinclair","Hargreaves","Whelan","Fitzgerald","Pryor","Drummond","Kerr","Lowe"],
 ITA:["Rossetti","Bianchi","Ferraro","Gallo","Conti","Marini","Moretti","Lombardi","Barbieri","Fontana","Greco","Sartori"],FRA:["Moreau","Lefèvre","Girard","Bonnet","Dupont","Lambert","Fontaine","Chevalier","Rousseau","Mercier"],GER:["Becker","Hoffmann","Schäfer","Koch","Richter","Krüger","Wolf","Neumann","Brandt","Vogel"],
 ESP:["García","Navarro","Ortega","Romero","Herrera","Castillo","Molina","Vidal"],NED:["de Jong","Bakker","Visser","Smit","Mulder","de Graaf","Kuiper","Bos"],BRA:["Silva","Oliveira","Costa","Pereira","Almeida","Ribeiro","Carvalho","Moura"],
 MEX:["Hernández","Ramírez","Torres","Flores","Vargas","Mendoza","Castañeda"],JPN:["Tanaka","Suzuki","Sato","Yamamoto","Nakamura","Kobayashi","Ito","Watanabe"],SCA:["Lindqvist","Andersen","Nyberg","Holm","Larsen","Berg","Dahl","Virtanen","Eklund","Strand"],
 CAN:["Tremblay","Gagnon","Roy","MacLeod","Fraser","Bouchard","Leblanc"],NZL:["Walsh","Ngata","Harrison","McRae","Burke"]};
const NAT_N={USA:"American",CAN:"Canadian",MEX:"Mexican",BRA:"Brazilian",ARG:"Argentine",GBR:"British",IRL:"Irish",FRA:"French",GER:"German",ITA:"Italian",ESP:"Spanish",NED:"Dutch",BEL:"Belgian",DEN:"Danish",SWE:"Swedish",FIN:"Finnish",NOR:"Norwegian",AUS:"Australian",NZL:"New Zealander",JPN:"Japanese",CHN:"Chinese",RSA:"South African",MON:"Monegasque",THA:"Thai",SUI:"Swiss",AUT:"Austrian",POR:"Portuguese",COL:"Colombian",BUL:"Bulgarian",CZE:"Czech",IND:"Indian",PAR:"Paraguayan",CAY:"Caymanian",BRB:"Barbadian",POL:"Polish"};
const NAT_POOL={USA:"USA",CAN:"CAN",MEX:"MEX",BRA:"BRA",ARG:"MEX",COL:"MEX",GBR:"GBR",IRL:"GBR",FRA:"FRA",BEL:"FRA",MON:"FRA",GER:"GER",AUT:"GER",SUI:"GER",ITA:"ITA",ESP:"ESP",POR:"ESP",NED:"NED",DEN:"SCA",SWE:"SCA",FIN:"SCA",NOR:"SCA",AUS:"AUS",NZL:"NZL",JPN:"JPN"};
// regional nationality mixes for generated fields
const NAT_MIX={us:["USA","USA","USA","USA","USA","USA","CAN","MEX"],eu:["GBR","GBR","ITA","FRA","GER","ESP","NED","SCA","SCA","BRA","USA","JPN","AUS","MEX","BEL","SUI"],aus:["AUS","AUS","AUS","NZL"],intl:["USA","GBR","ITA","FRA","GER","ESP","NED","SCA","BRA","JPN","AUS","MEX","CAN"]};
function genName(nat,seed){const p=NAT_POOL[nat]||"USA";const f=FN[p]||FN.USA,l=LN[p]||LN.USA;if(seed!==undefined)return hpick(f,seed+"f")+" "+hpick(l,seed+"l");return R.pick(f)+" "+R.pick(l);}
const SPONSOR_FIC=["Apex Lubricants","Hometown Pizza Co.","Big Ridge Lumber","Crossroads Tire & Auto","Thunderbolt Energy Drink","Summit Peak Roofing","Blue Line Logistics","Redline Brake Systems","Quik-Fix Hardware","Lakeshore Credit Union","Ironclad Insurance","Velocity Vapor-Free Coolant","Golden Harvest Feed & Seed","Stallion Trucking","Northstar Solar","Pinnacle Health Clinics","Riverside Ford","Mach 5 Car Wash","Bolt Wireless","Cardinal Steel","Trailhead Outdoors","FastLane Fuel Stops","Cobalt Data Systems","Harbor Freightways","Prime Cut Steakhouse","Granite State Windows","Nitro Coffee Roasters","Wildfire BBQ Sauce","Atlas Moving & Storage","Sunbelt Pools","Comet Cleaning Supply","Patriot Pest Control"];
const BIG_SPONSOR_FIC=["Titan Telecom","Velocity Bank","Aurora Airlines","Global Freight Corp","Zenith Energy","Starline Beverages","Nexus Software","Paramount Insurance","Horizon Petroleum","Meridian Watches"];
const ENG_FIRST=["Dale","Rusty","Marty","Gil","Wendell","Hank","Lou","Carla","Denise","Ray","Benny","Tom","Matteo","Pierre","Giles","Ingrid","Ken","Rob","Sophie","Andy"];
function genStaff(seed){return hpick(ENG_FIRST,seed+"e")+" "+hpick(LN.USA.concat(LN.GBR,LN.ITA),seed+"s");}
const TEAM_SUFFIX=["Racing","Motorsports","Racing Group","Competition","Performance","Racing Team"];
