/* ===================== STORYLINES: LIFE, MILESTONES, OWNERSHIP, RETIREMENT, SYSTEM ===================== */
EV({id:"first_win_trophy",t:"Your First Win",tag:"MILESTONE",st:["active"],once:1,cond:()=>G.st.races.some(r=>r.f===1)?{}:null,w:20,s:{start:()=>({x:"The trophy from your first win sits on the kitchen table. Your family can't stop looking at it.",ch:[["Give it to your parents",()=>{rel("fam",15);morale(5);return "Mom puts it on the mantel. It'll be there forever.";}],["Keep it in the shop as motivation",()=>{morale(4);gainSk("con",.3);return "It goes on the shelf above your toolbox. One down.";}],["Give it to your crew",()=>{rel("cc",10);return "The crew argues for an hour over who gets to take it home first.";}]]})}});
EV({id:"title_celebration",t:"Champion!",tag:"MILESTONE",st:["any"],cond:()=>{const t=G.st.titles.filter(x=>x.yr===G.yr||x.yr===G.yr-1).slice(-1)[0];return t&&!G.fl["cel"+t.yr+t.s]?{s:t.s,yr:t.yr}:null;},w:20,cd:0,s:{start:c=>({x:`You're the ${c.yr} ${esc(SER[c.s].n)} champion. The celebration is still going.`,ch:[["Party with the crew all night",()=>{G.fl["cel"+c.yr+c.s]=1;rel("cc",10);morale(10);return "Champagne, pizza, and a crew member asleep in the hauler at sunrise.";}],["Thank everyone personally",()=>{G.fl["cel"+c.yr+c.s]=1;rep(3);rel("fam",5);rel("t:"+G.car.tm,5);return "Handwritten notes to every crew member, sponsor and family member.";}],["Already thinking about next year",()=>{G.fl["cel"+c.yr+c.s]=1;gainSk("con",.5);return "Two hours after the title, you're asking about next year's car.";}]]})}});
EV({id:"start100",t:"100 Starts",tag:"MILESTONE",st:["active"],once:1,cond:()=>G.st.races.length>=100?{}:null,w:10,s:{start:()=>({x:"Your 100th career start. The team puts a special decal on the car.",ch:[["Reflect on the journey",()=>{morale(5);return `From ${esc(SER[G.st.races[0].s].n)} to here. What a ride.`;}]]})}});
EV({id:"partner",t:"Someone Special",st:["active"],not:["junior"],once:1,cond:()=>G.me.age>=20?{n:genName(G.me.nat)}:null,s:{start:c=>({x:`You meet ${esc(c.n)} at a friend's barbecue. They don't know anything about racing and couldn't care less that you drive race cars. You like that.`,
 ch:[["Ask them out",()=>{G.fl.partner=c.n;morale(8);rel("fam",3);later("partner_travel",R.int(20,40),{n:c.n});return "Dinner turns into a four-hour conversation.";}],["Focus on racing",()=>"Maybe another time."]]})}});
EV({id:"partner_travel",t:"The Travel Is Hard",valid:c=>G.fl.partner===c.n,s:{start:c=>({x:`${esc(c.n)} says the weekends apart are getting hard.`,ch:[["Bring them on the road",()=>{morale(5);G.me.hp=clamp(G.me.hp-3,0,100);later("partner_proposal",R.int(30,60),{n:c.n});return "They come to the races. The paddock adopts them.";}],["Promise more time at home",()=>{G.car.ap=Math.max(0,G.car.ap-1);morale(4);later("partner_proposal",R.int(30,60),{n:c.n});return "You block out off-weekends. It helps.";}],["Racing comes first",()=>{G.fl.partner=null;morale(-8);return "You break up. The silence at home is loud.";}]]})}});
EV({id:"partner_proposal",t:"The Question",valid:c=>G.fl.partner===c.n,s:{start:c=>({x:`You've been with ${esc(c.n)} for a long time now. You've got a ring in your firesuit pocket.`,ch:[["Propose in victory lane (or wherever)",()=>{G.fl.married=c.n;morale(15);fame(1);addNews(`${G.me.name} is engaged.`,true);return "They say yes! The crew sprays you both with champagne.";}],["Not yet",()=>"The ring stays in the pocket."]]})}});
EV({id:"family_wedding",t:"Family Wedding",st:["season"],cond:()=>({}),s:{start:()=>({x:"Your sister's wedding is the same weekend as a race.",ch:[["Fly in after qualifying, fly back for the race",()=>{G.me.hp=clamp(G.me.hp-10,0,100);rel("fam",8);return "You make the toast in your team polo. Your sister cries.";}],["Miss the wedding",()=>{rel("fam",-15);morale(-5);return "Your sister doesn't speak to you for a month.";}]]})}});
EV({id:"money_manager",t:"A Financial Adviser",st:["pro"],cond:()=>G.me.cash>cashScale()*10?{n:genName("USA")}:null,cd:200,s:{start:c=>({x:`${esc(c.n)}, a slick financial adviser who manages money for "lots of athletes," wants to take over your finances. Returns of 25% a year, guaranteed.`,
 ch:[["Hand over the money",()=>{const amt=Math.round(G.me.cash*.4);G.me.cash-=amt;G.fl.adviser={amt,n:c.n};later("adviser_result",R.int(10,25),{});return "\"You won't regret it,\" they say.";}],["Use a boring index fund instead",()=>{earn(Math.round(G.me.cash*.05),"Investment returns");return "Slow, steady, safe.";}],["No thanks",()=>"You keep your money where it is."]]})}});
EV({id:"adviser_result",t:"The Adviser",valid:()=>!!G.fl.adviser,s:{start:()=>{const a=G.fl.adviser;const scam=R.chance(.6);return {x:scam?`${esc(a.n)} has vanished. The accounts are empty. You're one of a dozen athletes who were scammed.`:`${esc(a.n)} actually delivered. Your investment has grown.`,ch:[["Continue",()=>{G.fl.adviser=null;if(scam){morale(-10);addNews(`A fictional financial adviser who scammed several athletes, including ${G.me.name}, has disappeared.`,true);return "Lesson learned the hard way.";}earn(Math.round(a.amt*1.25),"Investment return");return "Nice.";}]]};}}});
EV({id:"sponsor_scandal",t:"Sponsor in Trouble",st:["any"],not:["retired"],cond:()=>{const s=G.car.spons.find(x=>x.amt>0);return s?{n:s.n}:null;},cd:200,s:{start:c=>({x:`${esc(c.n)}, one of your sponsors (a fictional company), is in the news for all the wrong reasons: accused of cooking its books.`,
 ch:[["Drop them immediately",()=>{G.car.spons=G.car.spons.filter(x=>x.n!==c.n);rep(2);return "You remove their logo before the next race. The media praises the quick action.";}],["Wait for the facts",()=>{if(R.chance(.5)){rep(1);return "The accusations turn out to be overblown. Your loyalty is rewarded.";}G.car.spons=G.car.spons.filter(x=>x.n!==c.n);rep(-2);return "It's all true. Your association lingers in the headlines.";}]]})}});
EV({id:"injury_choice",t:"Road to Recovery",st:["active"],cond:()=>G.me.inj&&G.me.inj.w>=3?{}:null,cd:10,w:5,s:{start:()=>({x:`Doctors say you need about ${plural(G.me.inj.w,"week")} to heal your ${esc(G.me.inj.n)}. Your team is asking when you'll be back.`,
 ch:[["Follow the doctors' timeline",()=>{G.me.hp=clamp(G.me.hp+10,0,100);return "Patience. You'll be back at full strength.";}],["Push to come back early",()=>{G.me.inj.w=Math.max(1,Math.round(G.me.inj.w*.5));G.me.hp=clamp(G.me.hp-15,0,100);if(R.chance(.25)){G.me.pot=Math.max(60,G.me.pot-1);return "You're back early, but something never feels quite right again.";}return "You're back early. It hurts, but you're in the car.";}],["Spend the time in the simulator",()=>{gainSk("qul",.6);gainSk("con",.4);return "You can't drive, but you can study.";}]]})}});
EV({id:"crash_confidence",t:"Shaken",st:["active"],cond:()=>{const r=G.st.races.slice(-1)[0];return r&&/rash|Multi/.test(r.dnf||"")&&G.me.inj?{}:null;},cd:40,s:{start:()=>({x:"That crash was a big one. At night you replay the impact. You haven't told anyone.",ch:[["Talk to a sports psychologist",()=>{morale(6);gainSk("con",.4);return "It helps to say it out loud.";}],["Get back in a car as soon as possible",()=>{if(R.chance(.6)){morale(4);return "The first laps are scary. Then it's just driving again.";}morale(-4);return "You're tentative for weeks.";}]]})}});
EV({id:"burnout",t:"Running on Empty",st:["active"],cond:()=>G.me.hp<45||G.me.mor<30?{}:null,cd:20,s:{start:()=>({x:"You're exhausted. Travel, sponsors, testing, racing. Something has to give.",ch:[["Take a full week off",()=>{G.me.hp=clamp(G.me.hp+25,0,100);morale(10);G.car.ap=0;return "No phone. No racing. Just sleep and sunlight.";}],["Push through",()=>{G.me.hp=clamp(G.me.hp-5,0,100);gainSk("fit",.2);return "You grind it out.";}]]})}});
EV({id:"podcast",t:"Start a Podcast?",st:["pro"],once:1,cond:()=>G.me.fame>=20?{}:null,s:{start:()=>({x:"A producer wants to launch a racing podcast with you as host.",ch:[["Do it",()=>{fame(3);gainSk("med",1);G.fl.podcast=1;earn(cashScale()|0,"Podcast");return "Episode 1 hits the top of the sports charts.";}],["No time",()=>"You've got enough going on."]]})}});
EV({id:"driving_camp",t:"Your Own Driving Camp",st:["pro","retired"],once:1,cond:()=>G.me.fame>=25?{}:null,s:{start:()=>({x:"You could start a youth driving camp in your name.",ch:[["Start it",()=>{spend(cashScale()*2|0,"Camp setup");rel("fans",10);G.fl.camp=1;return "Thirty kids in karts on opening day. One of them is really, really fast.";}],["Not yet",()=>"Someday."]]})}});
EV({id:"movie_consultant",t:"Hollywood Calling",st:["top"],once:1,cond:()=>G.me.fame>=50?{}:null,s:{start:()=>({x:"A film studio making a racing movie wants you as a technical consultant and a cameo.",ch:[["Do it",()=>{earn(cashScale()*2|0,"Movie fee");fame(4);return "You spend a week teaching an actor how to sit in a car. Your cameo: 'Driver #3'.";}],["Pass",()=>"You'd rather race."]]})}});
EV({id:"business_offer",t:"Business Opportunity",st:["pro","retired"],cond:()=>G.me.cash>cashScale()*15?{b:R.pick(["a car dealership","a tire shop chain","a race shop","a racing school","a short track"])}:null,cd:200,s:{start:c=>({x:`A friend offers you a stake in ${esc(c.b)}.`,ch:[["Invest",()=>{const amt=cashScale()*6|0;spend(amt,"Investment");G.fl.biz=(G.fl.biz||0)+1;later("biz_return",R.int(26,52),{amt,b:c.b});return "You're a business owner.";}],["Pass",()=>"You stick to racing."]]})}});
EV({id:"biz_return",t:"Business Report",s:{start:c=>{const g=R.chance(.65);return {x:g?`${esc(c.b)} is doing well. A dividend arrives.`:`${esc(c.b)} is struggling.`,ch:[["Continue",()=>{if(g)earn(Math.round(c.amt*R.f(.3,.9)),"Dividend");else spend(Math.round(c.amt*.2),"Capital call");return "";}]]};}}});
/* ---------- team owner storylines ---------- */
function ownPick(){return (G.own||[]).length?R.pick(G.own):null;}
EV({id:"own_driver_raise",t:"Your Driver Wants a Raise",tag:"TEAM OWNER",st:["own"],cond:()=>{const o=ownPick();if(!o)return null;const t=G.TM[o.tid];const d=t.cars.map(c=>c.d).filter(x=>x&&x!=="me"&&G.D[x]&&!G.D[x].r)[0];return d?{tid:o.tid,d}:null;},s:{start:c=>{const o=ownOf(c.tid);return {x:`${D(c.d)}, who drives for ${esc(o.n)}, wants more money. Their agent mentions "other interest."`,ch:[["Give them a 20% raise",()=>{o.sal[c.d]=Math.round((o.sal[c.d]||10000)*1.2);rel("d:"+c.d,8);return "Happy driver, lighter bank account.";}],["Refuse",()=>{rel("d:"+c.d,-10);if(R.chance(.4)){const id=c.d;freeDriver(id);G.D[id].cy=0;return "They walk. You need a new driver.";}return "They grumble, but they stay.";}]]};}}});
EV({id:"own_pay_driver",t:"A Pay Driver Pitch",tag:"TEAM OWNER",st:["own"],cond:()=>{const o=ownPick();return o?{tid:o.tid,d:genName(R.pick(NAT_MIX.intl))}:null;},s:{start:c=>{const o=ownOf(c.tid);const amt=Math.round(ownOp(o.s)*.4/1000)*1000;return {x:`A wealthy family offers ${money(amt)} if their child, ${esc(c.d)}, gets a seat at ${esc(o.n)}. The kid is... not very fast.`,
 ch:[["Take the money (replace your weakest driver)",()=>{const t=G.TM[o.tid];const slot=t.cars.filter(x=>x.d!=="me").sort((a,b)=>(G.D[a.d]?G.D[a.d].o:0)-(G.D[b.d]?G.D[b.d].o:0))[0];if(!slot)return "There's no seat to give.";if(slot.d){delete o.sal[slot.d];freeDriver(slot.d);}const d=genDriverFor(o.s);d.n=c.d;d.o=clamp(SER[o.s].lvl-8,15,90);slot.d=d.id;d.tm=o.tid;d.s=o.s;d.num=slot.num;o.sal[d.id]=0;o.cash+=amt;return "The money's in the bank. Results might suffer.";}],["Decline",()=>{rep(1);return "Your team, your standards.";}]]};}}});
EV({id:"own_cc_poached",t:"Your Technical Director Is Poached",tag:"TEAM OWNER",st:["own"],cond:()=>{const o=(G.own||[]).find(x=>x.cc.r>=65);return o?{tid:o.tid}:null;},s:{start:c=>{const o=ownOf(c.tid);return {x:`A bigger team wants ${esc(o.cc.n)}, your top technical person at ${esc(o.n)}.`,ch:[["Match the offer",()=>{o.cash-=Math.round(ownOp(o.s)*.06);return "They stay.";}],["Let them go",()=>{o.cc.r=Math.max(40,o.cc.r-12);o.cc.n=genStaff(o.tid+absWk());return "You promote from within. It'll take time.";}]]};}}});
EV({id:"own_alliance",t:"Technical Alliance",tag:"TEAM OWNER",st:["own"],cond:()=>{const o=ownPick();if(!o)return null;const big=teamsOf(o.s).filter(t=>!t.own&&t.q>o.q+5).sort((a,b)=>b.q-a.q)[0];return big?{tid:o.tid,tm:big.id}:null;},cd:100,s:{start:c=>{const o=ownOf(c.tid);return {x:`${esc(tn(c.tm))} offers ${esc(o.n)} a technical alliance: their engineering data and parts, for a fee and some independence.`,ch:[["Sign the alliance",()=>{o.cash-=Math.round(ownOp(o.s)*.15);o.q=Math.min(SER[o.s].ql+10,o.q+3);G.TM[o.tid].q=o.q;return "Your cars get a lot faster, but you're now somebody's B-team.";}],["Stay independent",()=>"You'll build it your way."]]};}}});
EV({id:"own_prodigy",t:"A Prodigy Is Available",tag:"TEAM OWNER",st:["own"],cond:()=>{const o=ownPick();return o?{tid:o.tid}:null;},s:{start:c=>{const o=ownOf(c.tid);const n=genName(R.pick(NAT_MIX.us));return {x:`Scouts are raving about ${esc(n)}, a teenage phenom. You could sign them to a development deal for ${esc(o.n)}.`,ch:[["Sign them",()=>{const d=genDriverFor(o.s);d.n=n;d.by=G.yr-Math.max(SER[o.s].age,16);d.o=clamp(SER[o.s].lvl-3,15,90);d.pot=clamp(d.o+20,0,96);const t=G.TM[o.tid];const slot=t.cars.find(x=>!x.d);if(slot){slot.d=d.id;d.tm=o.tid;d.s=o.s;d.num=slot.num;o.sal[d.id]=Math.round(driverAsk(d,o.s)*.4);return `${esc(n)} goes straight into your empty car.`;}d.tm=null;d.s=null;d.cy=0;G.fl.prodigy=d.id;return `You sign ${esc(n)} to a development deal. When a seat opens, they're ready.`;}],["Pass",()=>"Someone else will take the chance."]]};}}});
EV({id:"team_broke",t:"The Team Is Broke",tag:"TEAM OWNER",s:{start:c=>{const o=ownOf(c.tid);if(!o)return null;return {x:`${esc(o.n)}'s bank account is deep in the red (${money(o.cash)}). Suppliers are calling.`,ch:[["Bail it out with your own money",()=>{const need=Math.min(G.me.cash,-o.cash+Math.round(ownOp(o.s)*.2));G.me.cash-=need;o.cash+=need;return "The team survives, for now.";}],["Cut the budget to the bone",()=>{o.bud=0;o.q=Math.max(20,o.q-3);G.TM[o.tid].q=o.q;return "Lean times.";}],["Sell the team",()=>({screen:()=>sellTeam(o)})]]};}}});
EV({id:"charter_sale",t:"Charter for Sale",tag:"TEAM OWNER",st:["own"],cond:()=>{const o=(G.own||[]).find(x=>x.s==="cup"&&!x.charter);return o?{tid:o.tid}:null;},cd:100,s:{start:c=>{const o=ownOf(c.tid);const p=Math.round(CHARTER_PRICE*R.f(.7,.95));return {x:`A struggling Cup team (fictional) is selling its charter for ${money(p)}, below market price.`,ch:[["Buy it",()=>{if(G.me.cash<p)return "You don't have the money.";spend(p,"Charter");o.charter=1;return "Your team now has a charter.";},G.me.cash<p&&"Not enough cash"],["Pass",()=>"Maybe next time."]]};}}});
/* ---------- retired ---------- */
EV({id:"tv_booth",t:"The Broadcast Booth",tag:"LIFE AFTER RACING",st:["retired"],once:1,cond:()=>G.me.fame>=20||careerTotals().w>=5?{}:null,s:{start:()=>({x:"A TV network offers you a job as a race analyst.",ch:[["Take the job",()=>{G.fl.tv=1;earn(Math.round(cashScale()*5+200000),"TV contract");fame(3);return "Your first broadcast goes well. You might be better at this than anyone expected.";}],["Pass",()=>"You'd rather watch from the couch."]]})}});
EV({id:"legends_race",t:"Legends Race",tag:"LIFE AFTER RACING",st:["retired"],cd:52,cond:()=>({}),s:{start:()=>({x:"A charity legends race invites retired champions for one more go.",ch:[["Race",()=>{if(R.chance(.35)){fame(2);return "You win, and you feel 25 again for about an hour.";}return "You finish mid-pack, laughing in your helmet.";}],["Wave the green flag instead",()=>{fame(1);return "Grand marshal duty. The crowd gives you a standing ovation.";}]]})}});
EV({id:"coach_offer",t:"Driver Coach",tag:"LIFE AFTER RACING",st:["retired"],once:1,cond:()=>({}),s:{start:()=>({x:"A young driver's family asks you to coach their kid.",ch:[["Coach them",()=>{earn(50000,"Coaching");rel("fans",4);return "The kid is raw but fearless. You see yourself.";}],["Decline",()=>"You're enjoying retirement."]]})}});
/* ---------- system / follow-ups ---------- */
EV({id:"net_callback",t:"A Callback",tag:"OPPORTUNITY",valid:c=>!!G.TM[c.tm],s:{start:c=>({x:`${esc(towner(c.tm))} of ${esc(tn(c.tm))} calls back. "We might have something for you."`,ch:[["Hear them out",()=>{const t=G.TM[c.tm];const o=mkOffer(t,myStock(t.s)>=teamNeed(t)-3?"race":"race",myStock(t.s)>=teamNeed(t)-3?{}:{pay:Math.round((SER[t.s].cost||200000)*.8/1000)*1000,sal:0,win:0});G.offers.push(o);return {screen:()=>negotiate(o)};}],["Not now",()=>"You thank them for thinking of you."]]})}});
EV({id:"debt",t:"In Debt",tag:"MONEY",s:{start:()=>({x:`You're ${money(-G.me.cash)} in the red. Creditors are calling.`,ch:[["Take a loan from family",()=>{G.me.cash+=Math.min(-G.me.cash+2000,40000);rel("fam",-6);G.fl.debtWk=0;return "Your family bails you out. Again.";}],["Sell equipment",()=>{G.me.cash+=Math.round(cashScale()*3);if(G.TM.priv)G.TM.priv.q=Math.max(20,G.TM.priv.q-3);G.fl.debtWk=0;return "The spares go. The car is slower.";}],["Work extra jobs",()=>{G.me.cash+=3000;G.me.hp=clamp(G.me.hp-15,0,100);G.fl.debtWk=0;return "Night shifts. You're exhausted, but solvent-ish.";}]]})}});
EV({id:"body_says_no",t:"The Body Says No",tag:"MILESTONE",s:{start:()=>({x:`You're ${G.me.age}. Your reflexes are a tick slower. The young drivers are fearless. Is it time?`,ch:[["Keep going",()=>{morale(2);return "Not yet. Not while you can still win.";}],["Retire at the end of the season",()=>{G.fl.retireEoY=1;addNews(`${G.me.name} announces this will be their final season.`,true);fame(2);return "The farewell tour begins.";}],["Retire now",()=>({screen:retireMenu})]]})}});
EV({id:"crossroads",t:"Season Over: What's Next?",tag:"CAREER",s:{start:()=>{const c=G.car;const s=SER[c.s];const pos=champPos(c.s,"me");const opts=(NEXT[c.s]||[]).filter(id=>!licenseBlock(id));
 const ch=opts.map(id=>{const n=SER[id];if(isPriv(id))return [`Move up to ${esc(n.n)} next year (own car)`,()=>{G.fl.nextPriv=id;return `Next season you'll run your own car in ${esc(n.n)}: about ${money(startCost(id))} per race. Start saving and hunting sponsors.`;},false,`${esc(n.desc)} · ~${money(startCost(id)*n.cal.length)} per season`];
  return [`Chase a ride in ${esc(n.n)}`,()=>{G.fl.askWk=0;generateOffers("fa");return {screen:offersScreen};},false,`Team seat or pay ride (${n.cost?"~"+money(n.cost)+" per season to buy in":"team-funded"})`];});
 ch.push(["Stay and run another season here",()=>"You'll be back next year. Unfinished business.",false,`${esc(s.n)}`]);
 ch.push(["Try a different discipline",()=>({screen:ownCarMenu}),false,"Karting, dirt, stock cars, road racing..."]);
 return {x:`Your ${esc(s.n)} season is done${pos?`: you finished <b>${ordinal(pos)}</b> in points`:""}. Every racer reaches this point: stay where you're comfortable, or step up to faster cars and tougher fields.`,ch};}}});
EV({id:"free_tryout",t:"A Tryout",tag:"OPPORTUNITY",st:["free"],cond:()=>{const sid=lastSeries();const ts=teamsOf(sid).filter(t=>!t.own&&!t.priv);return ts.length?{tm:R.pick(ts).id}:null;},cd:12,s:{start:c=>({x:`${esc(tn(c.tm))} needs a driver for a test session and invites you. A strong showing could turn into a ride.`,
 ch:[["Give it everything",()=>{const t=G.TM[c.tm];if(OVR(SER[t.s].disc)+R.gauss()*5>=teamNeed(t)-4){const o=mkOffer(t,"race",{note:"After your tryout",start:G.wk<40?G.yr:G.yr+1});G.offers.push(o);return {screen:()=>negotiate(o)};}rel("t:"+c.tm,3);return "Respectable, but they go another way. They'll remember you, though.";}],["Pass",()=>"You'll wait for something better."]]})}});
