/* ===================== STORYLINES: PRO RACING (on-track & contract stories may involve real drivers; off-track drama is fictional only) ===================== */
EV({id:"engineer_clash",t:"Setup Philosophy",st:["team"],cond:()=>({}),s:{start:()=>({x:`You want the car freer on entry. ${cc()}, your ${ccW()}, insists the data says tighter. The debrief is getting tense.`,
 ch:[["Trust the data",()=>{rel("cc",5);G.car.testB=(G.car.testB||0)+.4;return "You drive what they give you. The data was right, mostly.";}],["Insist on your setup",()=>{if(R.chance(.5+G.me.sk.fbk/250)){G.car.testB=(G.car.testB||0)+1;rel("cc",2);return "Your feel was right. The car comes alive.";}rel("cc",-6);G.car.testB=0;return "It's a disaster in practice. The silence in the debrief room is deafening.";}],["Find a compromise",()=>{rel("cc",2);G.car.testB=(G.car.testB||0)+.6;gainSk("fbk",.4);return "Half of each idea. It works better than either.";}]]})}});
EV({id:"teammate_quali",t:"Teammate Tension",st:["team"],cond:()=>{const m=mateId();return m?{d:m}:null;},s:{start:c=>({x:`In qualifying, ${D(c.d)} ${R.pick(["took the tow you were supposed to get","didn't let you by on their cool-down lap","got the newer parts this weekend"])}. Everyone in the team is waiting to see how you react.`,
 ch:[["Raise it privately with the team",()=>{rel("t:"+G.car.tm,2);rel("d:"+c.d,-2);return "The team promises it won't happen again. Your teammate gives you a cool nod.";}],["Call it out in the media",()=>{fame(2);rel("d:"+c.d,-12);rel("t:"+G.car.tm,-6);rel("media",3);addNews(`${G.me.name} publicly criticizes a teammate after qualifying.`,true);return "The quote makes headlines. The team is furious, the fans love the drama.";}],["Let your driving do the talking",()=>{rep(1);gainSk("qul",.4);return "You'll just be faster next week.";}]]})}});
EV({id:"media_rival",t:"Press Conference",st:["pro"],cond:()=>{const d=rivalD()||(G.car.s?standings(G.car.s).filter(r=>r.id!=="me")[0]:null)&&standings(G.car.s).filter(r=>r.id!=="me")[0].id;return d&&G.D[d]?{d}:null;},s:{start:c=>({x:`A reporter asks about ${D(c.d)}: "Are they the one to beat this year?"`,
 ch:[["\"They're great. I'm going to beat them anyway.\"",()=>{fame(2);rel("d:"+c.d,-3);return "Confident, not disrespectful. The quote runs everywhere.";}],["Praise them generously",()=>{rel("d:"+c.d,6);rep(1);return "They return the compliment later. Mutual respect.";}],["\"I don't think about other drivers.\"",()=>{rel("media",-1);return "The reporters sigh. Not much of a story.";}]]})}});
EV({id:"contact_aftermath",t:"Contact on Track",st:["pro"],cond:()=>{const d=anyD();return d?{d,fic:!G.D[d].r}:null;},s:{start:c=>({x:`You and ${D(c.d)} made contact battling for position last race. ${c.fic?`They walk up to you in the garage, still in their firesuit, clearly fuming.`:`Afterward, ${esc(nmShort(c.d))} told reporters they weren't happy with how you raced them.`}`,
 ch:[["Apologize: your fault",()=>{rel("d:"+c.d,8);rep(1);return "Clean and classy. Things settle down.";}],["Stand your ground: hard racing",()=>{rel("d:"+c.d,-10);fame(1);G.fl.feud=c.d;later("feud_round2",R.int(3,7),{d:c.d});return "You think it was a racing incident and you say so. This isn't over.";}],["Watch the replay together",()=>{if(R.chance(.5)){rel("d:"+c.d,5);return "You both see it differently, but you agree to give each other room.";}rel("d:"+c.d,-4);return "Watching it again just makes things worse.";}]]})}});
EV({id:"feud_round2",t:"Round Two",valid:c=>G.car.s&&G.D[c.d]&&G.D[c.d].s===G.car.s,s:{start:c=>({x:`Late in the race you find yourself side by side with ${D(c.d)} again. Last time it ended badly.`,
 ch:[["Give them room",()=>{rel("d:"+c.d,8);rep(1);return "You race them clean and finish nose to tail. Afterward there's a fist bump. Feud over.";}],["Race them hard, no quarter",()=>{if(R.chance(.5)){rel("d:"+c.d,-5);fame(2);return "You make the pass stick and drive off. The broadcast replays it all week.";}rel("d:"+c.d,-10);G.stats.crashes++;rep(-1);return "You both end up in the wall. The officials call you both to the hauler.";}]]})}});
EV({id:"penalty_contact",t:"Called to the Stewards",st:["pro"],cond:()=>({}),s:{start:()=>({x:"The officials review your move from last race and want to see you. A penalty is possible.",
 ch:[["Bring the data and argue your case",()=>{if(R.chance(.5+G.me.sk.med/300))return "They accept your explanation. No further action.";spend(cashScale()*.3|0,"Fine");return "They don't buy it. Fine issued.";}],["Accept responsibility",()=>{spend(cashScale()*.15|0,"Fine");rep(1);return "A small fine and a reputation for honesty.";}],["Criticize the officials publicly",()=>{spend(cashScale()*.5|0,"Fine");fame(2);rep(-2);rel("media",2);return "The fans cheer you on. The officials fine you again for the comments.";}]]})}});
EV({id:"manufacturer_program",t:"Manufacturer Development Program",st:["ladder","grass"],cond:()=>OVR()>=50&&G.me.age<=24?{m:R.pick(["Toyota","Chevrolet","Ford","Honda","Porsche","BMW","Ferrari","Mercedes"])}:null,cd:120,s:{start:c=>({x:`${esc(c.m)}'s driver development people want you in their program: sim access, fitness coaching, and a word in the right ears. They want loyalty in return.`,
 ch:[["Join the program",()=>{G.fl.mfr=c.m;gainSk("qul",.6);gainSk("fit",.6);rep(3);addNews(`${G.me.name} joins the ${c.m} driver development program.`,true);return `You're officially a ${esc(c.m)} development driver. Doors are opening.`;}],["Keep your options open",()=>"You stay independent. Your agent says it might cost you, or might pay off later."]]})}});
EV({id:"sponsor_conflict",t:"Sponsor Day vs. Test Day",st:["pro","team"],cond:()=>mySponsor()?{}:null,s:{start:()=>({x:`${esc(mySponsor().n)} wants you at a corporate event on the same day as the team's test.`,
 ch:[["Go to the sponsor event",()=>{mySponsor().sat=clamp(mySponsor().sat+10,0,100);G.car.testB=0;rel("cc",-3);return "Handshakes, photos and a speech. The sponsor is very happy.";}],["Go to the test",()=>{mySponsor().sat=clamp(mySponsor().sat-12,0,100);G.car.testB=(G.car.testB||0)+1;return "The car is better. The sponsor is not.";}],["Do both: fly back and forth",()=>{G.me.hp=clamp(G.me.hp-12,0,100);mySponsor().sat=clamp(mySponsor().sat+5,0,100);G.car.testB=(G.car.testB||0)+.5;return "Two cities in one day. Exhausting, but everyone's happy.";}]]})}});
EV({id:"sponsor_unhappy",t:"An Unhappy Sponsor",st:["any"],not:["retired"],cond:()=>{const s=G.car.spons.find(x=>x.sat<35);return s?{n:s.n}:null;},s:{start:c=>({x:`${esc(c.n)}'s marketing director calls. "We're not seeing the return we expected."`,
 ch:[["Promise more appearances",()=>{const s=G.car.spons.find(x=>x.n===c.n);if(s)s.sat+=20;G.me.hp=clamp(G.me.hp-6,0,100);return "Your calendar fills up with store visits and golf outings.";}],["Promise better results",()=>{const s=G.car.spons.find(x=>x.n===c.n);if(s)s.sat+=8;G.fl.promise=1;return "\"We'll hold you to that.\"";}],["Let them walk",()=>{G.car.spons=G.car.spons.filter(x=>x.n!==c.n);return "They're gone. You'll find someone else.";}]]})}});
EV({id:"sponsor_bonus",t:"Bonus Offer",st:["any"],not:["retired"],cond:()=>{const s=G.car.spons.find(x=>x.sat>=75);return s?{n:s.n}:null;},s:{start:c=>({x:`${esc(c.n)} loves the partnership. They offer a performance bonus: hit a target and they double the check.`,
 ch:[["Accept: a top five this month",()=>{G.fl.spBonus={n:c.n,wk:absWk()+5};later("sponsor_bonus_check",5,{n:c.n});return "Game on.";}],["Ask for a guaranteed raise instead",()=>{const s=G.car.spons.find(x=>x.n===c.n);if(s&&R.chance(.5)){s.amt=Math.round(s.amt*1.15);return "They agree to a 15% raise.";}return "They'd rather do the bonus. Maybe next year.";}]]})}});
EV({id:"sponsor_bonus_check",t:"Bonus Time",s:{start:c=>{const ok=G.st.races.some(r=>r.f<=5&&r.yr*52+r.wk>=absWk()-5);return {x:ok?`You hit the target. ${esc(c.n)} pays up.`:`No top five. ${esc(c.n)} is disappointed.`,ch:[["Continue",()=>{const s=G.car.spons.find(x=>x.n===c.n);if(ok&&s){earn(Math.round(s.amt*.5),"Sponsor bonus");s.sat+=5;}else if(s)s.sat-=5;return "";}]]};}}});
EV({id:"driver_council",t:"Drivers' Council",st:["top"],once:1,cond:()=>G.me.rep>=50?{}:null,s:{start:()=>({x:"Your fellow drivers want you to represent them on the drivers' council: safety, schedules, rules and money.",
 ch:[["Accept the role",()=>{rep(4);rel("media",3);G.fl.council=1;return "You spend late nights on conference calls about tire allocation and SAFER barriers. People respect you more.";}],["Decline: focus on driving",()=>"You've got enough on your plate."]]})}});
EV({id:"contract_rumor_you",t:"Linked With a Rival Team",st:["pro"],cond:()=>{if(!G.car.s)return null;const t=teamsOf(G.car.s).filter(x=>x.id!==G.car.tm&&!x.own&&!x.priv&&x.q>=myQ(G.car.tm)-3);return t.length?{tm:R.pick(t).id}:null;},s:{start:c=>({x:`A respected journalist reports that ${esc(tn(c.tm))} has asked about your availability. Your phone won't stop buzzing.`,
 ch:[["Deny everything",()=>{rel("t:"+G.car.tm,3);return "You say you're happy where you are. Your team appreciates it.";}],["\"I'm focused on this season.\" (Wink.)",()=>{rel("t:"+c.tm,4);rel("t:"+G.car.tm,-3);fame(1);if(R.chance(.5)){G.offers.push(mkOffer(G.TM[c.tm],"race",{note:"They called after the rumor."}));G.notes.push(`📄 ${esc(tn(c.tm))} made you an offer.`);}return "The rumor grows legs.";}],["Use it to push your team for a raise",()=>{if(G.car.con&&G.car.con.sal&&R.chance(.45)){G.car.con.sal=Math.round(G.car.con.sal*1.12);rel("t:"+G.car.tm,-2);return "Your team quietly bumps your salary 12%.";}rel("t:"+G.car.tm,-6);return "Your team doesn't take kindly to the pressure.";}]]})}});
EV({id:"cc_poached",t:"Your Crew Chief Gets an Offer",st:["team"],cond:()=>G.car.cc&&G.car.cc!=="Dad"?{}:null,s:{start:()=>({x:`${cc()} pulls you aside. A bigger team has offered them a job. "I'd rather stay with you. But that's a lot of money."`,
 ch:[["Ask the team to match it",()=>{if(R.chance(.55)){rel("cc",12);return "The team matches. Your partnership gets stronger.";}G.car.cc=genStaff("cc"+absWk());delete G.rel.cc;return "The team won't pay. You get a new crew chief and start from scratch.";}],["Tell them to take it",()=>{G.car.cc=genStaff("cc"+absWk());delete G.rel.cc;rep(1);return "You hug it out. The new person is good, but it takes time to gel.";}],["Chip in from your own salary",()=>{spend(cashScale()*2|0,"Crew chief raise");rel("cc",20);return "They're stunned. \"I'll never forget this.\"";}]]})}});
EV({id:"pit_mistakes",t:"Pit Road Woes",st:["team"],cond:()=>G.car.s&&PIT_SERIES[G.car.s]?{}:null,s:{start:()=>({x:"Two races in a row, your pit crew has cost you spots with slow stops. The crew is down. The team asks what you think.",
 ch:[["Back the crew publicly",()=>{rel("t:"+G.car.tm,3);rel("cc",4);return "The crew practices every morning. The stops get faster. They'll go to war for you.";}],["Demand changes",()=>{carUp(.6);rel("cc",-4);return "Two crew members get swapped out. The stops improve. The garage is colder.";}],["Bring donuts to pit practice",()=>{rel("cc",3);morale(2);return "Sometimes leadership is just showing up with breakfast.";}]]})}});
EV({id:"budget_cut",t:"Budget Cuts",st:["team"],cond:()=>onTeam()&&!G.TM[G.car.tm].r?{}:null,s:{start:()=>({x:`${esc(towner(G.car.tm))} calls a team meeting: a sponsor left, and the budget for the rest of the year is being cut.`,
 ch:[["Bring your own sponsor money to the team",()=>{const s=mySponsor();if(s){spend(Math.round(s.amt*.3),"Team support");rel("t:"+G.car.tm,10);return "Your contribution keeps the car competitive.";}carUp(-2);return "You don't have enough sponsorship to help.";}],["Accept it and make do",()=>{carUp(-2);return "Fewer tests, older parts. You'll have to drive around it.";}],["Start looking at other teams",()=>{rel("t:"+G.car.tm,-5);G.fl.askWk=0;return "Your agent starts making calls.";}]]})}});
EV({id:"upgrade_package",t:"The New Package",st:["team"],cond:()=>({}),s:{start:()=>({x:"The team brings a big upgrade package this weekend: new aero, new suspension. It's fast in the wind tunnel, untested on track.",
 ch:[["Run it",()=>{if(R.chance(.6)){carUp(1.5);return "It works! You gain real speed.";}carUp(-.5);return "It's a step backward. The team has to go back to the drawing board.";}],["Test it first, race the old spec",()=>{G.car.testB=(G.car.testB||0)+.5;if(R.chance(.7)){carUp(1);return "After a careful test, the package goes on next week. Solid gain.";}return "The test shows it doesn't work. Good thing you waited.";}]]})}});
EV({id:"rookie_hazing",t:"Rookie Welcome",st:["pro"],once:1,cond:()=>{const d=ficD(x=>G.yr-x.by>=30);return d?{d}:null;},s:{start:c=>({x:`Veteran ${D(c.d)} makes it clear in the drivers' meeting that rookies need to "learn their place."`,
 ch:[["Earn their respect on track",()=>{rel("d:"+c.d,5);gainSk("dfd",.5);return "You race them hard and clean all weekend. Afterward: \"Not bad, rookie.\"";}],["Say something back",()=>{rel("d:"+c.d,-10);fame(1);return "The room goes quiet. A few drivers smirk. You've made an enemy.";}],["Ask them for advice",()=>{rel("d:"+c.d,10);gainSk("crf",.4);return "They're surprised, then flattered. Turns out they're a good teacher.";}]]})}});
EV({id:"fitness_coach",t:"Elite Fitness Coach",st:["pro"],cond:()=>G.me.sk.fit<80?{n:genName("GBR")}:null,s:{start:c=>({x:`${esc(c.n)}, a trainer who has worked with top drivers, offers a year-long program: ${money(cashScale()*3|0)}.`,
 ch:[["Sign up",()=>{spend(cashScale()*3|0,"Trainer");gainSk("fit",2);G.me.hp=100;return "Brutal. Effective. Your neck is the size of a tree trunk.";}],["Pass",()=>"You'll stick to your own routine."]]})}});
EV({id:"performance_coach",t:"A Mental Edge",st:["pro"],cond:()=>({}),s:{start:()=>({x:"A sports psychologist offers sessions on visualization, pressure and focus.",
 ch:[["Try it",()=>{spend(cashScale()|0,"Sessions");gainSk("con",.8);morale(5);return "Breathing exercises, mental laps, pressure routines. You feel calmer under the lights.";}],["\"My head is fine.\"",()=>"You'll handle the pressure your way."]]})}});
EV({id:"charity_event",t:"Charity Ride-Along Day",st:["pro"],cond:()=>({}),s:{start:()=>({x:"A children's hospital charity asks if you'll host a ride-along day at the track.",
 ch:[["Absolutely",()=>{fame(2);rel("fans",8);morale(6);return "You give 40 hot laps and get more out of it than any of the kids.";}],["Donate money instead",()=>{spend(cashScale()|0,"Donation");rel("fans",3);return "A generous check, quietly delivered.";}]]})}});
EV({id:"hometown_parade",t:"Hometown Hero",st:["pro"],once:1,cond:()=>G.me.fame>=35?{}:null,s:{start:()=>({x:`${esc(G.me.home.split(",")[0])} wants to throw you a parade and put your name on a sign at the edge of town.`,
 ch:[["Ride in the parade",()=>{fame(3);rel("fans",10);rel("fam",8);morale(8);return "Your whole town lines Main Street. Your elementary school teacher hands you a drawing you made at age eight: a race car.";}],["Politely ask for a scholarship fund instead",()=>{rep(2);rel("fans",8);return "The Racing Dreams Scholarship is founded in your name.";}]]})}});
EV({id:"tv_reality",t:"Reality TV Offer",st:["pro"],cond:()=>G.me.fame>=30?{}:null,cd:150,s:{start:()=>({x:"A streaming service wants to film a behind-the-scenes series about your season. Big money, cameras everywhere.",
 ch:[["Sign on",()=>{earn(cashScale()*4|0,"TV deal");fame(5);G.fl.tvShow=1;later("tv_reality_followup",12,{});return "The cameras arrive Monday.";}],["Decline",()=>"You'd rather keep the garage private."]]})}});
EV({id:"tv_reality_followup",t:"The Show Airs",s:{start:()=>({x:"The series airs. The editors made a few of your heated radio messages look worse than they were.",ch:[["Laugh it off",()=>{fame(3);gainSk("med",.5);return "Your fanbase doubles. Nobody remembers the context, only the personality.";}],["Complain about the editing",()=>{rel("media",-3);fame(1);return "Complaining makes the clip go viral again.";}]]})}});
EV({id:"esports_invite",t:"Sim Racing Invitational",st:["any"],not:["retired"],cond:()=>G.me.sim>=1?{}:null,s:{start:()=>({x:"You're invited to a televised sim racing invitational with pro drivers and top sim racers.",
 ch:[["Go all in",()=>{const r=G.me.sk.qul+G.me.sim*5+R.gauss()*10;if(r>=75){fame(3);earn(cashScale()|0,"Prize");return "You win the invitational! The sim community is impressed.";}fame(1);return "You finish mid-pack. The sim racers are terrifyingly good.";}],["Stream it casually",()=>{fame(1);rel("fans",4);return "You crash out on lap one and laugh about it. Great content.";}]]})}});
EV({id:"tire_test",t:"Tire Test Invitation",st:["pro"],cond:()=>({}),s:{start:()=>({x:"The tire supplier invites you to a two-day tire test. Tons of laps, no pressure, valuable seat time.",
 ch:[["Accept",()=>{seatTime(G.car.s?tkt(SER[G.car.s].cal[0][0]):"road",1.5);gainSk("tir",.7);gainSk("fbk",.5);return "Hundreds of laps. You know more about tires than ever.";}],["Rest instead",()=>{G.me.hp=clamp(G.me.hp+10,0,100);return "A few days off. You needed it.";}]]})}});
EV({id:"fp1_outing",t:"FP1 Outing",st:["reserve"],cond:()=>({}),cd:8,s:{start:()=>({x:`${esc(tn(G.car.tm))} gives you the car for the first practice session this weekend.`,
 ch:[["Push for a headline time",()=>{if(R.chance(.15)){rel("t:"+G.car.tm,-6);return "You go off and damage the floor. Not the impression you wanted.";}rel("t:"+G.car.tm,6);rep(2);seatTime("road",1.2);return "You finish the session ahead of one of the regular drivers. The team notices.";}],["Do the test program perfectly",()=>{rel("t:"+G.car.tm,4);gainSk("fbk",.8);seatTime("road",1);return "Every item on the run plan, perfectly. The engineers love you.";}]]})}});
EV({id:"reserve_sim",t:"Simulator Duty",st:["reserve"],cond:()=>({}),cd:6,s:{start:()=>({x:"The team needs you in the simulator all night to develop the setup for the next race.",
 ch:[["Grind it out",()=>{gainSk("qul",.4);gainSk("fbk",.4);rel("t:"+G.car.tm,3);return "At 4 a.m. you find something: a setup direction that works. The race team uses it.";}],["Ask for a seat-time deal in return",()=>{if(R.chance(.4)){G.fl.reserveRace=1;rel("t:"+G.car.tm,1);return "They promise you an extra outing. Keep doing the work.";}rel("t:"+G.car.tm,-2);return "\"Just do your job.\"";}]]})}});
EV({id:"daytona_alliance",t:"Drafting Alliance",st:["stock"],cond:()=>G.car.s&&SER[G.car.s].tier>=5&&anyD()?{d:anyD()}:null,s:{start:c=>({x:`Before the next superspeedway race, ${D(c.d)} suggests working together in the draft.`,
 ch:[["Shake on it",()=>{rel("d:"+c.d,6);gainSk("drf",.5);return "You plan to work together until the final lap. After that, it's every driver for themselves.";}],["Stick with your manufacturer teammates",()=>{rel("t:"+G.car.tm,3);return "Team first.";}]]})}});
EV({id:"team_orders_fallout",t:"The Team Orders Fallout",st:["team"],cond:()=>G.fl.ignoredTO&&!G.fl.toFall?{}:null,s:{start:()=>({x:`${esc(towner(G.car.tm))} calls you to the office about the radio call you ignored.`,
 ch:[["Apologize",()=>{G.fl.toFall=1;rel("t:"+G.car.tm,5);return "\"Don't let it happen again.\"";}],["Stand by it: you race to win",()=>{G.fl.toFall=1;rel("t:"+G.car.tm,-8);fame(2);rep(1);return "Some respect you for it. Your boss isn't one of them.";}]]})}});
EV({id:"caution_controversy",t:"A Controversial Call",st:["pro"],cond:()=>G.st.races.length&&G.st.races[G.st.races.length-1].f>1&&G.st.races[G.st.races.length-1].f<=3?{}:null,s:{start:()=>({x:"A late caution or safety car last race wiped out your lead. Replays suggest it was unnecessary.",
 ch:[["Speak out",()=>{spend(cashScale()*.2|0,"Fine");fame(2);rel("media",2);return "\"That was ridiculous.\" The fans agree. The officials fine you for it.";}],["Stay diplomatic",()=>{rep(1);return "\"That's racing.\" You'll get it back.";}]]})}});
EV({id:"spotter_issue",t:"Spotter Trouble",st:["stock"],cond:()=>G.car.s&&SER[G.car.s].tier>=4?{n:genName("USA")}:null,s:{start:c=>({x:`Your spotter, ${esc(c.n)}, missed a call that nearly put you in the wall.`,
 ch:[["Give them another chance",()=>{rel("cc",2);return "They're dialed in the next week. Loyalty pays.";}],["Hire a veteran spotter",()=>{spend(cashScale()*.5|0,"New spotter");gainSk("drf",.4);gainSk("crf",.2);return "The new spotter has been on the roof for 25 years. Calm, precise, perfect.";}]]})}});
EV({id:"heat_wave",t:"Heat Wave",st:["season"],not:["kart"],cond:()=>G.wk>=24&&G.wk<=34?{}:null,s:{start:()=>({x:"Temperatures in the car will hit 140°F this weekend. Drivers are being warned about heat exhaustion.",
 ch:[["Heat training all week",()=>{gainSk("fit",.6);G.me.hp=clamp(G.me.hp-4,0,100);return "Sauna sessions in a firesuit. Brutal, but you're ready.";}],["Rest and hydrate",()=>{G.me.hp=clamp(G.me.hp+8,0,100);return "IVs and sleep. You'll be fine.";}]]})}});
EV({id:"illegal_part",t:"A Gray Area",st:["team","priv"],cond:()=>tierNow()>=3?{}:null,cd:120,s:{start:()=>({x:`${cc()} shows you a part. "It's... creative. Technically the rulebook doesn't say we can't. Technically."`,
 ch:[["Run it",()=>{carUp(1.5);G.fl.grayPart=1;later("illegal_caught",R.int(2,6),{});return "The car is noticeably faster.";}],["Not worth the risk",()=>{rep(.5);return "You'd rather win clean.";}]]})}});
EV({id:"illegal_caught",t:"Inspection Findings",valid:()=>G.fl.grayPart&&!!G.car.s,s:{start:()=>{const caught=R.chance(.45);return {x:caught?"Officials find the part in post-race inspection. The penalty is coming.":"Officials looked right at the part and moved on. You got away with it, but the rule is being clarified for next week.",ch:[["Continue",()=>{G.fl.grayPart=0;if(caught){const st=G.S[G.car.s];if(st&&st.tab.me){st.tab.me.p=Math.max(0,st.tab.me.p-(SER[G.car.s].pts==="nascar"?40:SER[G.car.s].pts==="grass"?40:10));}rep(-3);rel("media",-3);carUp(-1.5);spend(cashScale()|0,"Fine");addNews(`${G.me.name}'s team penalized after inspection.`,true);return "Points docked, fine paid, part confiscated.";}carUp(-1.5);return "The part comes off. No harm done.";}]]};}}});
EV({id:"data_offer",t:"Stolen Data",st:["pro"],cd:200,cond:()=>({e:genName("GBR")}),s:{start:c=>({x:`An engineer named ${esc(c.e)}, from a rival (fictional) team, offers you a USB drive with their setup data. "For a price."`,
 ch:[["Refuse and report it",()=>{rep(3);rel("media",2);return "The engineer is fired. You're seen as a person of integrity.";}],["Refuse quietly",()=>"You walk away and say nothing."],["Take it",()=>{G.car.testB=(G.car.testB||0)+2;later("data_scandal",R.int(4,10),{});return "The data is gold. You feel sick about it.";}]]})}});
EV({id:"data_scandal",t:"The Data Scandal",s:{start:()=>({x:"An investigation into leaked data has found your name. Your team is furious.",ch:[["Come clean",()=>{rep(-5);rel("t:"+G.car.tm,-10);spend(cashScale()*2|0,"Fine");addNews(`${G.me.name} fined for using leaked data from a rival team.`,true);return "You admit it. A fine and a ruined reputation, but you can rebuild.";}],["Deny everything",()=>{if(R.chance(.5))return "The investigation runs out of evidence.";rep(-10);G.car.sit=true;later("suspension_end",3,{});addNews(`${G.me.name} suspended for three weeks in the data scandal.`,true);return "The evidence is clear. You're suspended for three weeks.";}]]})}});
EV({id:"suspension_end",t:"Back in the Car",s:{start:()=>({x:"Your suspension is over.",ch:[["Get back to work",()=>{G.car.sit=false;return "Time to rebuild trust.";}]]})}});
EV({id:"merch_deal",t:"Merchandise Deal",st:["pro"],cond:()=>G.me.fame>=25?{}:null,s:{start:()=>({x:"A merchandise company wants to put your face on T-shirts, hats and diecast cars.",ch:[["Sign the deal",()=>{earn(cashScale()*2|0,"Merch deal");fame(2);return "Your first diecast arrives in the mail. You put it on the shelf next to your first trophy.";}],["Design the merch yourself",()=>{earn(cashScale()|0,"Merch");rel("fans",6);return "Your designs are a hit with the fans.";}]]})}});
EV({id:"video_game",t:"Video Game Rating",st:["top"],once:1,cond:()=>({}),s:{start:()=>({x:"Your rating in the official video game came out. It's... lower than you think it should be.",ch:[["Complain online (jokingly)",()=>{fame(2);rel("fans",5);return "The developers bump your rating in a patch and the fans love the bit.";}],["Use it as motivation",()=>{morale(4);return "You print it and tape it to your sim rig.";}]]})}});
EV({id:"cross_dirt",t:"Midweek Dirt Race",st:["pro"],not:["dirt"],cond:()=>!G.car.con||G.car.con.side?{}:null,s:{start:()=>({x:"A dirt track promoter offers you a guest ride in a midweek Sprint Car show. Lots of pros do it to stay sharp.",
 ch:[["Go play in the dirt",()=>{gainSk("drt",1);gainSk("crf",.4);const r=G.me.sk.drt+R.gauss()*10;if(r>=60){fame(2);rep(1);return "You win the feature! The dirt crowd adopts you as one of their own.";}if(R.chance(.08)){const inj=hurt(2);return `You flip in turn three. The car's ruined and you're hurt: ${esc(inj)}.`;}return "Mid-pack and filthy. Best night you've had in months.";}],["Team says no",()=>{rel("t:"+G.car.tm,2);return "Your team breathes a sigh of relief.";}]]})}});
EV({id:"early_extension",t:"An Early Extension",st:["team"],cond:()=>G.car.con&&G.car.con.end===G.yr&&!G.car.next&&relOf("t:"+G.car.tm)>=15&&G.TM[G.car.tm]&&!G.TM[G.car.tm].own?{}:null,s:{start:()=>({x:`${esc(towner(G.car.tm))} wants to extend your deal before silly season gets going.`,
 ch:[["Let's talk",()=>{const o=mkOffer(G.TM[G.car.tm],"race",{note:"Early extension",start:G.yr+1,int:75});G.offers.push(o);return {screen:()=>negotiate(o)};}],["Wait and test the market",()=>{rel("t:"+G.car.tm,-3);return "You want to see what's out there.";}]]})}});
EV({id:"teammate_replaced_rumor",t:"Rumor Mill",st:["team","realser"],cond:()=>{const m=mateId();if(!m)return null;const others=fieldIds(d=>d.tm!==G.car.tm);if(!others.length)return null;return {d:m,d2:R.pick(others)};},s:{start:c=>({x:`Word in the paddock is that ${esc(tn(G.car.tm))} has talked to ${D(c.d2)} about next season. Either you or ${D(c.d)} could be the one squeezed out.`,
 ch:[["Ask the team directly",()=>{if(relOf("t:"+G.car.tm)>=10)return "\"You're not going anywhere.\" Relief.";rel("t:"+G.car.tm,-2);return "The answer is vague. Too vague.";}],["Put in extra hours at the shop",()=>{rel("t:"+G.car.tm,4);gainSk("fbk",.3);return "Everyone sees you there at 7 a.m. every day.";}]]})}});
EV({id:"safety_crusade",t:"After the Crash",st:["pro"],cond:()=>{const d=ficD();return d?{d}:null;},cd:150,s:{start:c=>({x:`${D(c.d)} had a violent crash into an unprotected wall last week. They walked away, barely. Drivers are angry.`,
 ch:[["Lead the call for better barriers",()=>{rep(3);rel("media",4);rel("d:"+c.d,8);return "Within months, the series installs energy-absorbing barriers at three tracks. You may have saved lives.";}],["Visit them and keep it private",()=>{rel("d:"+c.d,12);return "They appreciate it more than you know.";}]]})}});
EV({id:"former_rival_retires",t:"An Old Rival Hangs It Up",st:["pro"],cond:()=>{const a=Object.keys(G.rel).filter(k=>k.startsWith("d:")&&G.D[k.slice(2)]&&G.D[k.slice(2)].ret&&!G.D[k.slice(2)].r&&Math.abs(G.rel[k])>=10);return a.length?{d:a[0].slice(2)}:null;},cd:100,s:{start:c=>({x:`${D(c.d)}, someone you battled with for years, has retired.`,ch:[["Send a message of respect",()=>{rel("d:"+c.d,15);rep(1);return "They reply: \"You made me better.\"";}],["Say nothing",()=>"Some rivalries don't end with a handshake."]]})}});
EV({id:"pole_record",t:"Track Record Chance",st:["season"],cond:()=>G.car.s&&tierNow()>=3?{}:null,s:{start:()=>({x:"Conditions are perfect for qualifying this weekend: cool air, grippy track. The track record is within reach.",ch:[["Go for the record",()=>{G.car.testB=(G.car.testB||0)+.6;gainSk("qul",.4);if(R.chance(.3)){fame(2);return "You smash the track record in practice! Qualifying should be good.";}return "Close, but not quite. You'll have a strong setup though.";}],["Focus on race trim",()=>{G.car.testB=(G.car.testB||0)+.4;return "Race setup it is.";}]]})}});
EV({id:"throwback",t:"Throwback Paint Scheme",st:["stock"],cond:()=>tierNow()>=5?{}:null,s:{start:()=>({x:"For the throwback weekend, you can pick a retro paint scheme.",ch:[["Honor your first race car",()=>{rel("fans",6);fame(1);return "The fans who remember your Saturday-night days love it.";}],["Let the fans vote",()=>{rel("fans",8);return "The fans pick a gloriously ugly 1980s design. It sells out in merch.";}],["Whatever the sponsor wants",()=>{if(mySponsor())mySponsor().sat+=8;return "The sponsor is thrilled.";}]]})}});
