/* ===================== STORYLINES: GRASSROOTS & JUNIOR ===================== */
EV({id:"promoter_bonus",t:"Promoter's Proposition",st:["grass"],not:["kart"],cond:()=>G.car.s&&tkt(SER[G.car.s].cal[0][0])!=="kart"?{p:genName("USA")}:null,s:{start:c=>({x:`${esc(c.p)}, who runs the local track, leans on your trailer. "Fans love your car. Run our midweek special and I'll slip you appearance money. Bring a crowd and there's more."`,
 ch:[["Run the special",()=>{earn(cashScale()*.8|0,"Appearance money");fame(1);G.me.hp=clamp(G.me.hp-8,0,100);seatTime(tkt(SER[G.car.s].cal[0][0]),.5);return "A wild midweek show. You finish fourth, sign autographs for an hour and drive home at 2 a.m.";}],
  ["Ask for more money first",()=>{if(R.chance(.5)){earn(cashScale()*1.4|0,"Appearance money");return `${esc(c.p)} grumbles and pays. You put on a show.`;}rel("media",-1);return `"Forget it, kid. Plenty of guys would race for free." The offer's gone.`;}],
  ["Pass: rest and work on the car",()=>{G.car.testB=(G.car.testB||0)+.5;return "You spend the night in the garage instead. The car will be better for it.";}]]})}});
EV({id:"tech_flag",t:"Trouble in Tech",st:["grass"],cond:()=>({o:genName("USA")}),s:{start:c=>({x:`Post-race tech. Inspector ${esc(c.o)} frowns at your ${R.pick(["carburetor spacer","rear spring","ride height","tire durometer"])}. "This looks out of spec."`,
 ch:[["Calmly ask them to measure again",()=>{if(R.chance(.6+G.me.sk.fbk/300)){rep(1);return "Second measurement: legal by a hair. The inspector shrugs and waves you through.";}spend(cashScale()*.3|0,"Fine");return "Still out. A fine and a stern warning.";}],
  ["Argue loudly",()=>{if(R.chance(.3)){fame(1);return "The crowd at the tech shed cheers you on. The inspector gives up.";}spend(cashScale()*.4|0,"Fine");rep(-1);rel("media",-2);return "Bad idea. You lose your points from the night and pay a fine.";}],
  ["Accept the penalty",()=>{rep(.5);return "You take your medicine. The old-timers nod: that kid has class.";}]]})}});
EV({id:"veteran_parts",t:"Hand-Me-Down Parts",st:["grass"],cond:()=>({v:genName("USA")}),s:{start:c=>({x:`${esc(c.v)}, a gray-haired local legend who won here for twenty years, waves you over. "I'm hanging it up. Got a shed full of parts. They're yours if you want 'em, just promise you'll win with 'em."`,
 ch:[["Accept gratefully",()=>{if(G.car.tm==="priv")carUp(1.5);rel("fans",3);return "Shocks, gears, spare noses and a notebook of setups going back to 1998. Priceless.";}],["Offer to pay him something",()=>{spend(cashScale()*.5|0,"Parts");if(G.car.tm==="priv")carUp(2);rep(1);return `"Respect," he says, shaking your hand. He throws in his favorite set of shocks.`;}],
  ["Ask him to coach you instead",()=>{gainSk("crf",.8);gainSk("sht",.6);later("veteran_mentor_followup",R.int(6,12),{});return "He grins. \"Now that I can do.\" You spend Sunday afternoons learning his lines.";}]]})}});
EV({id:"veteran_mentor_followup",t:"The Old Man's Last Lesson",s:{start:()=>({x:"Your mentor watches from the grandstands, arms crossed. Afterward he says: \"You're quick. But you race the guy next to you instead of the track. Race the track.\"",ch:[["Take it to heart",()=>{gainSk("con",1);gainSk("crf",.5);return "Something clicks. Smoother hands, calmer mind.";}],["Argue that racing is about beating people",()=>{gainSk("ovt",.8);return "He laughs. \"Then go beat 'em.\"";}]]})}});
EV({id:"local_paper",t:"Front Page of the Sports Section",st:["grass"],cond:()=>G.st.races.length>=2?{}:null,s:{start:()=>({x:`The ${esc(G.me.home.split(",")[0])} newspaper wants to profile the local kid going racing. The reporter asks what your dream is.`,
 ch:[["\"The Daytona 500. Or Indy. Or Formula 1. All of it.\"",()=>{fame(2);rel("media",3);return "The headline reads: LOCAL RACER DREAMS BIG. Your mom buys ten copies.";}],["\"Win this weekend. That's all I think about.\"",()=>{rep(1);rel("media",1);return "The old racers at the track appreciate the humility.";}],["Mention your sponsors (or that you need some)",()=>{if(R.chance(.4)){const sp=newSponsorOffer();return {screen:()=>sponsorOfferScreen(sp)};}fame(1);return "No calls yet, but your name's out there.";}]]})}});
EV({id:"family_strain",t:"Kitchen Table Talk",st:["grass"],not:["own"],cond:()=>G.me.bg!=="rich"&&G.me.cash<cashScale()*6?{}:null,s:{start:()=>({x:"Your parents sit you down. Racing is eating the family budget alive. Dad has worked overtime for months. \"We want this for you. We just don't know how much longer we can do it.\"",
 ch:[["Get a part-time job and pay your own way",()=>{earn(cashScale()*2|0,"Job savings");G.me.hp=clamp(G.me.hp-5,0,100);rel("fam",8);morale(-2);return "Early shifts before school or work, races on weekends. Exhausting, but it's yours.";}],["Sell the spare engine",()=>{earn(cashScale()*3|0,"Sold parts");if(G.car.tm==="priv")carUp(-1.5);return "It hurts to watch it go, but the bills are paid.";}],["Promise to find sponsors",()=>{rel("fam",3);G.fl.sponPromise=1;later("family_strain_followup",8,{});return "You start a list of every business in town.";}],["Ask your grandparents for help",()=>{earn(cashScale()*2.5|0,"Family loan");rel("fam",-2);return "Grandpa writes a check and says, \"Pay me back with a trophy.\"";}]]})}});
EV({id:"family_strain_followup",t:"The Promise",s:{start:()=>({x:G.car.spons.length?"You kept your word: sponsors are on the car. Dad tears up a little at the track.":"Eight weeks later: no sponsors. Your parents don't say anything, which is worse.",ch:[[G.car.spons.length?"Hug your dad":"Work harder",()=>{if(G.car.spons.length){rel("fam",10);morale(5);return "He pretends there's dust in his eye.";}morale(-4);gainSk("med",.6);return "You start cold-calling businesses in the next county too.";}]]})}});
EV({id:"school_exams",t:"Exams vs. Race Weekend",st:["junior"],cond:()=>({}),s:{start:()=>({x:"Finals week lines up with the biggest race of the month. Your teachers aren't impressed by \"I'm a race car driver.\"",
 ch:[["Study hard, skip testing",()=>{rel("fam",6);G.car.testB=0;morale(-1);return "Straight A's... well, B-plus. Your parents are thrilled.";}],["Race first, cram later",()=>{gainSk("crf",.4);rel("fam",-6);return "You barely pass. Mom is not happy.";}],["Bring the textbooks to the track",()=>{gainSk("con",.3);rel("fam",2);return "Flashcards between heat races. It sort of works.";}]]})}});
EV({id:"rival_dumped_you",t:"Bumped and Run",st:["grass"],cond:()=>{const d=ficD();return d?{d}:null;},s:{start:c=>({x:`${D(c.d)} moved you out of the way for a spot last weekend, a classic bump and run. Their crew laughed about it in the pits.`,
 ch:[["Return the favor next week",()=>{rel("d:"+c.d,-15);later("payback_result",R.int(1,3),{d:c.d});return "You circle the date. Payback is coming.";}],["Talk to them like an adult",()=>{if(R.chance(.55)){rel("d:"+c.d,10);rep(1);return `${esc(nm(c.d))} admits it was a cheap shot. You shake hands.`;}rel("d:"+c.d,-5);return `${esc(nm(c.d))} shrugs. "That's racing."`;}],["Let it go and beat them on speed",()=>{gainSk("con",.4);morale(-1);return "Your mechanic nods. \"Beat 'em on the stopwatch.\"";}]]})}});
EV({id:"payback_result",t:"Payback",s:{start:c=>({x:`Feature race, ten laps to go. ${D(c.d)} is right in front of you. You've got a run into turn three.`,
 ch:[["Put the bumper to them",()=>{if(R.chance(.5)){rel("d:"+c.d,-10);fame(2);rep(-1);return "They spin. The crowd roars, half cheering and half booing. Officials send you to the back, but the message is delivered.";}spend(cashScale()*.4|0,"Repairs");rel("d:"+c.d,-10);return "You both wreck. Two torn-up cars and a long night of repairs.";}],["Pass them clean",()=>{rep(2);rel("d:"+c.d,5);gainSk("ovt",.5);return "You get the run and drive right around them. The best kind of revenge.";}]]})}});
EV({id:"pit_confrontation",t:"An Angry Racing Dad",st:["grass","junior"],cond:()=>{const d=ficD();return d?{d}:null;},s:{start:c=>({x:`${esc(nm(c.d))}'s father storms over to your pit after the feature, red-faced. "Your kid wrecked mine! Who's paying for that nose?"`,
 ch:[["Stay calm and apologize for the contact",()=>{rep(1);rel("d:"+c.d,4);return "He calms down. The track officials, watching, are impressed.";}],["Get your own family involved",()=>{rel("d:"+c.d,-10);rel("fam",-3);fame(1);return "It turns into a shouting match by the concession stand. The track bans both dads for a week.";}],["Show him the video: it wasn't your fault",()=>{if(R.chance(.6)){rel("d:"+c.d,2);return "He watches it twice, mumbles something, and walks away.";}rel("d:"+c.d,-6);return "He doesn't care what the video says.";}]]})}});
EV({id:"engine_builder",t:"Engine Builder's Offer",st:["grass"],cond:()=>G.car.tm==="priv"?{b:genName("USA").split(" ")[1]+" Racing Engines"}:null,s:{start:c=>({x:`${esc(c.b)} offers a fresh motor at cost if you run their decal and tell everyone where the power came from.`,
 ch:[["Deal",()=>{spend(cashScale()*1.2|0,"Engine");carUp(2.5);rel("sp:"+c.b,10);return "The new motor screams. You're quicker everywhere.";}],["Ask to pay over time",()=>{carUp(2);G.fl.engineDebt=cashScale()*1.5|0;later("engine_debt",10,{b:c.b});return "They agree. The bill comes later.";}],["No thanks",()=>"You stick with your old motor."]]})}});
EV({id:"engine_debt",t:"The Engine Bill",s:{start:c=>({x:`${esc(c.b)} calls about the engine payment: ${money(G.fl.engineDebt||1000)}.`,ch:[["Pay it",()=>{spend(G.fl.engineDebt||1000,"Engine bill");G.fl.engineDebt=0;rep(1);return "Paid in full. Your word is good.";}],["Ask for more time",()=>{rep(-2);rel("sp:"+c.b,-10);if(G.TM.priv)carUp(-1);return "They take back some parts. Word gets around that you're slow to pay.";}]]})}});
EV({id:"trailer_trouble",t:"Broken Down on the Interstate",st:["grass"],cond:()=>({}),s:{start:()=>({x:"The tow truck's transmission dies 60 miles from the track. It's 2 p.m. and the drivers' meeting is at 5.",
 ch:[["Call every racer you know for a tow",()=>{if(R.chance(.6)){rel("fans",3);return "A rival family stops and hauls your car the rest of the way. Racing people are the best people.";}morale(-3);return "Nobody's free. You miss the race.";}],["Pay for an emergency rental",()=>{spend(cashScale()*.6|0,"Rental truck");return "Expensive, but you make the drivers' meeting with ten minutes to spare.";}],["Fix it on the side of the road",()=>{gainSk("fbk",.6);if(R.chance(.4))return "Duct tape and determination. You make it.";morale(-3);return "You can't fix it. Long night.";}]]})}});
EV({id:"mentor_champ",t:"The Track Champion",st:["grass","junior"],cond:()=>({v:genName("USA")}),s:{start:c=>({x:`${esc(c.v)}, a seven-time track champion who once ran a few national touring races, offers to coach you for the rest of the season.`,
 ch:[["Pay for weekly coaching",()=>{spend(cashScale()*1.5|0,"Coaching");gainSk("crf",1);gainSk("con",.8);gainSk("rdc",.4);gainSk("sht",.4);return "Hours of video review and laps in the passenger seat of a street car. You learn a lot.";}],["Offer to work in his shop in exchange",()=>{gainSk("fbk",1);gainSk("crf",.5);G.me.hp=clamp(G.me.hp-5,0,100);return "Sweeping floors, rebuilding shocks, soaking up wisdom.";}],["Politely decline",()=>"You'd rather learn on your own."]]})}});
EV({id:"chassis_offer",t:"A New Chassis",st:["grass"],cond:()=>G.car.tm==="priv"?{}:null,s:{start:()=>({x:"A chassis builder offers you a brand-new car at a discount. Their cars are winning everywhere this year.",
 ch:[["Buy it",()=>{spend(cashScale()*2.5|0,"New chassis");carUp(3.5);return "Fresh welds, new geometry. The car is a weapon.";}],["Buy a used one from a top team",()=>{spend(cashScale()*1.2|0,"Used chassis");carUp(1.8);return "A bit tired, but it won races last year.";}],["Keep your old car",()=>{gainSk("fbk",.3);return "You know every bolt on it. That counts for something.";}]]})}});
EV({id:"viral_video",t:"Gone Viral",st:["grass","ladder"],cond:()=>G.st.races.length>=3?{}:null,s:{start:()=>({x:"Your in-car camera from last week's race, with a three-wide save on the last lap, has a million views overnight.",
 ch:[["Lean in: start posting regularly",()=>{fame(4);gainSk("med",.8);rel("fans",6);return "Your follower count explodes. Sponsors start paying attention.";}],["Stay humble: just say thanks",()=>{fame(2);rep(1);return "People like the humility.";}],["Use it to pitch sponsors",()=>{const sp=newSponsorOffer();sp.amt=Math.round(sp.amt*1.3);return {screen:()=>sponsorOfferScreen(sp)};}]]})}});
EV({id:"scholarship",t:"Rising Star Scholarship Shootout",st:["grass","junior"],cond:()=>G.me.age<=22&&G.st.races.length>=4?{}:null,cd:60,s:{start:()=>({x:"A national racing scholarship invites twelve young drivers to a two-day shootout. The prize is a funded season in the next series up, plus coaching.",
 ch:[["Go for it",()=>{const r=OVR()+R.gauss()*6+G.me.sk.med/10;if(r>=56){G.fl.scholar=G.yr;const amt=cashScale()*20;earn(amt,"Scholarship");rep(4);fame(3);addNews(`${G.me.name} wins the Rising Star Scholarship shootout.`,true);return "You win it! Fastest in the car, best in the interviews. The check is huge.";}rep(1);gainSk("qul",.5);return "You make the final four but come up short. The judges tell you to come back next year.";}],["Skip it: focus on your season",()=>"You stay home and work on your car."]]})}});
EV({id:"county_fair",t:"County Fair Special",st:["grass"],not:["kart"],cond:()=>({}),s:{start:()=>({x:"The county fair is running a figure-8 and demolition-style 'run what you brung' race with a $2,000 to win purse. Your mechanic grins. \"We have that old junker in the back...\"",
 ch:[["Enter the junker!",()=>{if(R.chance(.35+OVR()/250)){earn(2000,"Fair purse");fame(2);return "You win the figure-8! The local TV station interviews you holding a giant check.";}if(R.chance(.15)){const inj=hurt(1);return `You T-bone a minivan at the crossover and get banged up: ${esc(inj)}.`;}fame(1);return "You lose a wheel on lap 6. The crowd loved it anyway.";}],["Watch from the grandstand with a funnel cake",()=>{morale(4);return "A rare night off. You laugh until your stomach hurts.";}]]})}});
EV({id:"local_diner",t:"The Diner Owner",st:["grass"],cond:()=>({n:R.pick(["Rosie's Diner","Big Al's BBQ","Main Street Pizza","Hank's Tire & Lube","Twin Oaks Hardware"])}),s:{start:c=>({x:`The owner of ${esc(c.n)} has been watching you race for years. "I can't do much. But I can do something."`,
 ch:[["Put their name on the car",()=>{G.car.spons.push({n:c.n,amt:cashScale()*3|0,sat:70,lvl:1,duty:1});rel("sp:"+c.n,10);return `${esc(c.n)} goes on the rear quarter panel. Free meals on race nights too.`;}],["Ask for free meals instead",()=>{G.me.hp=clamp(G.me.hp+5,0,100);morale(3);return "Unlimited pancakes. Your crew is very happy.";}]]})}});
EV({id:"trailer_theft",t:"Stolen",st:["grass","priv"],cd:150,cond:()=>G.car.tm==="priv"?{}:null,s:{start:()=>({x:"You walk outside on Saturday morning and the trailer is gone. Car, tools, spares, everything.",
 ch:[["Post it everywhere online",()=>{if(R.chance(.5)){fame(2);rel("fans",5);return "The racing community is incredible. It's found two counties over by Wednesday, mostly intact.";}carUp(-4);spend(cashScale()*2|0,"Replacement parts");return "It's never found. You start over with borrowed parts.";}],["File an insurance claim",()=>{carUp(-2);earn(cashScale()|0,"Insurance");return "The insurance money doesn't cover everything, but it's a start.";}]]})}});
EV({id:"kart_shop",t:"The Kart Shop",st:["kart"],cond:()=>({n:R.pick(["Apex Kart Works","Velocity Karting","Precision Kart Shop","Podium Karts"])}),s:{start:c=>({x:`${esc(c.n)} offers you a factory-supported seat for the next few races: their best chassis, their tuner, but you have to run their colors and help with customer days.`,
 ch:[["Accept",()=>{carUp(2);G.me.hp=clamp(G.me.hp-5,0,100);gainSk("fbk",.5);return "Factory support! Your kart is suddenly very fast.";}],["Stay independent",()=>"You keep your own program. Freedom matters."]]})}});
EV({id:"move_to_europe",t:"Move to Europe?",st:["kart","junior"],once:1,cond:()=>G.me.age>=12&&G.me.age<=16?{}:null,s:{start:()=>({x:"A European karting team scout watched you at a national event. \"If you want Formula 1, you need to race in Europe. Italy, Belgium, the big championships. It's expensive and lonely. But it's the path.\"",
 ch:[["Move to Italy with the team",()=>{G.fl.euro=1;spend(cashScale()*4|0,"Moving costs");gainSk("rdc",1.5);gainSk("crf",1);rep(3);rel("fam",-5);return "You move into a tiny flat near the kart factory. The level is unreal, and you get better every week.";}],["Stay in America",()=>{rel("fam",5);return "You'll take the American route: maybe Road to Indy, maybe stock cars.";}]]})}});
EV({id:"dad_crewchief",t:"Dad Wants to Be Crew Chief",st:["grass"],once:1,cond:()=>G.car.tm==="priv"?{}:null,s:{start:()=>({x:"Your dad has been turning wrenches since you started. Now he wants to call the shots on setup and strategy. He knows a lot, but you've been learning things he doesn't know.",
 ch:[["Let him run it",()=>{rel("fam",10);G.car.cc="Dad";gainSk("fbk",.3);return "He's in heaven. Some of his calls are brilliant; some are from 1985.";}],["Hire a real crew chief",()=>{spend(cashScale()*1.5|0,"Crew chief");G.car.cc=genStaff("cc"+absWk());rel("fam",-6);carUp(1);return "Dad is hurt, but he understands. The new guy is sharp.";}],["Make it a partnership",()=>{rel("fam",5);gainSk("fbk",.5);return "You split decisions. Sometimes it's chaos, sometimes it's magic.";}]]})}});
EV({id:"fan_kid",t:"Your Biggest Fan",st:["grass","ladder"],cond:()=>G.me.fame>=8?{}:null,s:{start:()=>({x:"A seven-year-old in a homemade firesuit with your number on it waits by your hauler. He's too shy to speak.",
 ch:[["Give him your gloves",()=>{fame(1);rel("fans",8);morale(5);return "His face lights up like a Christmas tree. His mom posts the photo and it goes everywhere.";}],["Let him sit in the car",()=>{rel("fans",6);morale(6);return "He grips the wheel and makes engine noises. You remember being that kid.";}]]})}});
EV({id:"protest_win",t:"Protested",st:["grass"],cond:()=>G.st.races.some(r=>r.f===1&&r.yr===G.yr)&&ficD()?{d:ficD()}:null,s:{start:c=>({x:`${D(c.d)} files a protest against your win, claiming your engine isn't legal. Tearing it down costs money, and if you refuse, you forfeit.`,
 ch:[["Tear it down",()=>{spend(cashScale()*.5|0,"Teardown");if(R.chance(.9)){rep(2);rel("d:"+c.d,-8);return "Legal. Every part. You collect the protest fee and a lot of respect.";}rep(-4);return "Something's out by a few thousandths. You lose the win.";}],["Refuse and forfeit",()=>{rep(-3);return "People will talk. You keep your secrets.";}]]})}});
EV({id:"midnight_garage",t:"Midnight in the Garage",st:["grass","priv"],cond:()=>({f:genName("USA")}),s:{start:c=>({x:`Your best friend ${esc(c.f)} shows up at 11 p.m. with pizza and a toolbox. "Figured you could use a hand." The car needs a full rebuild before Saturday.`,
 ch:[["Pull an all-nighter together",()=>{G.car.testB=(G.car.testB||0)+.8;G.me.hp=clamp(G.me.hp-10,0,100);morale(5);return "At 6 a.m. the car is done. You fall asleep on a pile of tires.";}],["Send them home and sleep",()=>{G.me.hp=clamp(G.me.hp+5,0,100);return "You'll finish tomorrow. Mostly.";}]]})}});
EV({id:"bad_fuel",t:"Bad Fuel",st:["grass"],cond:()=>({}),s:{start:()=>({x:"Half the pit area is sputtering: a bad batch of fuel from the track pumps. Your car is coughing too.",
 ch:[["Drain it and buy race fuel from a rival",()=>{spend(cashScale()*.2|0,"Race fuel");rep(1);return "Expensive, but you're one of the few cars running right. You finish strong.";}],["Run it and hope",()=>{if(R.chance(.5))return "It clears up after a few laps. Lucky.";if(G.car.tm==="priv")carUp(-1);return "The motor pings all night. It'll need a freshen.";}]]})}});
EV({id:"track_closing",t:"The Track Is Closing",st:["grass"],cd:200,cond:()=>({t:R.pick(["Cedar Valley Speedway","Thunder Road Raceway","Riverside Speedway","Copper Creek Clay"])}),s:{start:c=>({x:`${esc(c.t)}, where you ran your first laps, is being sold to developers. The last race night is a big one.`,
 ch:[["Lead a petition to save it",()=>{fame(2);rel("fans",8);if(R.chance(.25)){addNews(`Local racers save ${c.t} from closing.`,true);return "Against all odds, a group of local businesses buys the track. It's saved!";}return "Thousands sign. The sale goes through anyway, but people remember you fought.";}],["Win the last race ever held there",()=>{if(R.chance(.35+OVR()/300)){fame(2);morale(8);return "You win the final race ever held there. You take a chunk of the start-finish line home.";}morale(-2);return "You finish fifth. Somebody else will be in the history books.";}]]})}});
EV({id:"banger_invite",t:"Invite to a Big Grassroots Race",st:["grass"],cond:()=>({}),s:{start:()=>({x:"A promoter invites you to a big-money special a few states away. The top racers in the region will be there.",
 ch:[["Make the trip",()=>{spend(cashScale()*.6|0,"Travel");const r=OVR()+R.gauss()*8;if(r>=SER[G.car.s].lvl+6){earn(cashScale()*3|0,"Prize money");rep(3);fame(2);return "You win the whole thing against the best in the region!";}if(r>=SER[G.car.s].lvl){earn(cashScale()|0,"Prize money");rep(1);return "A top-five finish against a stacked field. People noticed.";}seatTime("sht",.5);return "A rough night: mid-pack, but you learned a lot.";}],["Stay home",()=>"Not worth the gas money."]]})}});
EV({id:"junior_media_training",t:"Media Training",st:["junior","grass"],cond:()=>({}),s:{start:()=>({x:"A family friend who works in TV offers to teach you how to do interviews: hit the sponsors, smile, don't say anything dumb.",ch:[["Take the lessons",()=>{gainSk("med",1.5);return "\"Well, the Hometown Tire & Lube Chevrolet was really good today...\" You're a natural.";}],["Nah, just be yourself",()=>{fame(1);return "Your awkward, honest interviews become a local favorite.";}]]})}});
