/* ===================== SCREENS: stats, standings, browser, achievements, endings ===================== */
function careerTotals(filter){const rs=G.st.races.filter(filter||(()=>true));return {st:rs.length,w:rs.filter(r=>r.f===1).length,pod:rs.filter(r=>r.f<=3).length,t5:rs.filter(r=>r.f<=5).length,t10:rs.filter(r=>r.f<=10).length,pol:rs.filter(r=>r.st===1).length,led:sum(rs.map(r=>r.led||0)),fl:rs.filter(r=>r.fl).length,dnf:rs.filter(r=>r.dnf).length,as:rs.length?r1(avg(rs.map(r=>r.st))):0,af:rs.length?r1(avg(rs.map(r=>r.f))):0};}
function careerScreen(){const c=careerTotals();const m=G.me;const titles=G.st.titles;
 show(`<h2>Career: ${esc(m.name)}${m.nick?` "${esc(m.nick)}"`:""}</h2><p>Age ${m.age} · ${esc(m.home)} · ${G.st.seasons.filter(s=>!s.oo).length} seasons · career earnings ${money(m.earned)}</p>
 ${tiles([{l:"Starts",v:c.st},{l:"Wins",v:c.w,h:c.st?Math.round(c.w/c.st*100)+"%":""},{l:"Podiums",v:c.pod},{l:"Top 5 / 10",v:`${c.t5} / ${c.t10}`,sm:1},{l:"Poles",v:c.pol},{l:"Laps led",v:c.led},{l:"Fastest laps",v:c.fl},{l:"DNFs",v:c.dnf},{l:"Avg start / finish",v:`${c.as} / ${c.af}`,sm:1},{l:"Championships",v:titles.length,h:titles.map(t=>t.yr+" "+esc(SER[t.s].sh)).slice(-3).join(", ")},{l:"Crown jewels",v:G.st.cj.length},{l:"Legacy",v:legacyScore(),h:legacyTier(legacyScore())}])}`,[
  {t:"Season by season",icon:"📅",tile:1,f:seasonsScreen},{t:"Totals by series",icon:"🗂️",tile:1,f:bySeriesScreen},{t:"Race log",icon:"📝",tile:1,f:()=>raceLog(0)},{t:"Crown jewels",icon:"👑",tile:1,f:crownScreen},{t:"Records",icon:"📈",tile:1,f:recordsScreen},{t:"Achievements",icon:"🏅",tile:1,f:achScreen},{t:"Back",cls:"hi",f:hub}]);}
function seasonsScreen(){const rows=G.st.seasons.slice().reverse().map(s=>({cells:[s.yr,esc(SER[s.s].sh)+(s.oo?" (one-off)":""),esc(s.tm),s.st,s.w,s.pd,s.t5,s.pol,s.dnf,s.af,s.oo?"-":(s.pos?ordinal(s.pos):"-")+(s.ch?" 🏆":"")],hl:!!s.ch}));
 const cur=Object.keys(G.S).filter(sid=>G.st.races.some(r=>r.yr===G.yr&&r.s===sid)).map(sid=>{const rs=G.st.races.filter(r=>r.yr===G.yr&&r.s===sid);const c=careerTotals(r=>r.yr===G.yr&&r.s===sid);return {cells:[G.yr+"*",esc(SER[sid].sh),esc(rs[rs.length-1].tmn||""),c.st,c.w,c.pod,c.t5,c.pol,c.dnf,c.af,SER[sid].oneoff||rs.every(r=>r.oo)?"-":ordinal(champPos(sid,"me")||0)]};});
 show(`<h2>Season by season</h2>${table(["Year","Series","Team","St","W","Pod","T5","Pole","DNF","Avg F","Pos"],cur.concat(rows))}<p class="dim">* current season in progress</p>`,[{t:"Back",cls:"hi",f:careerScreen}]);}
function bySeriesScreen(){const ids=[...new Set(G.st.races.map(r=>r.s))];show(`<h2>Totals by series</h2>${table(["Series","St","W","Pod","T5","Pole","Led","DNF","Avg F","Titles"],ids.map(sid=>{const c=careerTotals(r=>r.s===sid);return [esc(SER[sid].sh),c.st,c.w,c.pod,c.t5,c.pol,c.led,c.dnf,c.af,G.st.titles.filter(t=>t.s===sid).length];}))}`,[{t:"Back",cls:"hi",f:careerScreen}]);}
function raceLog(pg){const rs=G.st.races.slice().reverse();const per=25;const page=rs.slice(pg*per,pg*per+per);
 show(`<h2>Race log</h2><p>${rs.length} starts. Page ${pg+1} of ${Math.max(1,Math.ceil(rs.length/per))}.</p>${table(["Year","Event","Series","St","Fin","Led","Note"],page.map(r=>({cells:[r.yr,esc(r.ev)+(r.cj?" 👑":""),esc(SER[r.s].sh),r.st,r.f===1?"<b>1</b>":r.f,r.led||"",r.dnf?`<span class="r">${esc(r.dnf)}</span>`:(r.fl?"FL":"")],hl:r.f===1})))}`,
  [pg>0?{t:"Newer",f:()=>raceLog(pg-1)}:null,(pg+1)*per<rs.length?{t:"Older",f:()=>raceLog(pg+1)}:null,{t:"Back",cls:"hi",f:careerScreen}]);}
function crownScreen(){const all=[];SERIES_LIST.forEach(s=>s.cal.forEach((c,ci)=>{if(c[3])all.push({s:s.id,ci,n:c[2]});}));const seen={};const list=all.filter(x=>{if(seen[x.n])return false;seen[x.n]=1;return true;});
 show(`<h2>Crown jewels</h2><p>The races every driver wants on their résumé.</p>${table(["Race","Starts","Best","Wins"],list.map(x=>{const rs=G.st.races.filter(r=>r.ev===x.n);return {cells:[esc(x.n),rs.length,rs.length?Math.min(...rs.map(r=>r.f)):"-",rs.filter(r=>r.f===1).length?`<b class="gold">${rs.filter(r=>r.f===1).map(r=>r.yr).join(", ")}</b>`:"-"],hl:rs.some(r=>r.f===1)};}))}`,[{t:"Back",cls:"hi",f:careerScreen}]);}
function recordsScreen(){const ss=G.st.seasons.filter(s=>!s.oo);const bw=ss.slice().sort((a,b)=>b.w-a.w)[0];const ba=ss.filter(s=>s.st>=5).sort((a,b)=>a.af-b.af)[0];const rs=G.st.races;
 let streak=0,best=0;rs.forEach(r=>{if(r.f===1){streak++;best=Math.max(best,streak);}else streak=0;});const backWin=rs.filter(r=>r.f===1).sort((a,b)=>b.st-a.st)[0];
 const allTime={};Object.values(G.D).forEach(d=>{if(d.c.w>0)allTime[d.id]=d.c.w;});const topAI=Object.keys(allTime).sort((a,b)=>allTime[b]-allTime[a]).slice(0,5);
 show(`<h2>Records</h2>${table(["Record","Value"],[["Most wins in a season",bw?`${bw.w} (${bw.yr} ${esc(SER[bw.s].sh)})`:"-"],["Best average finish",ba?`${ba.af} (${ba.yr} ${esc(SER[ba.s].sh)})`:"-"],["Longest win streak",best],["Win from furthest back",backWin?`started ${ordinal(backWin.st)}: ${esc(backWin.ev)} ${backWin.yr}`:"-"],["Biggest payday career earnings",money(G.me.earned)],["Highest overall rating",Math.round(G.fl.peakOvr||OVR())]])}
 <h3>Most wins by rivals (in this career)</h3>${table(["Driver","Wins"],topAI.map(id=>[esc(nm(id)),allTime[id]]))}`,[{t:"Back",cls:"hi",f:careerScreen}]);}
function ratingsScreen(){const m=G.me;const ds=["kart","stock","dirt","open","sports"];
 show(`<h2>Driver ratings</h2>${tiles(ds.map(d=>({l:DISC_N[d],v:rb(OVR(d))})).concat([{l:"Potential",v:m.pot>=90?"Elite":m.pot>=84?"High":m.pot>=78?"Good":"Solid",h:"Your natural ceiling"},{l:"Superlicense",v:slpTotal()+"/40",h:"last 3 seasons"},{l:"Health",v:Math.round(m.hp)},{l:"Morale",v:Math.round(m.mor)}]))}
 ${statGrid()}<p>Traits: ${m.traits.map(t=>`<b>${TRAITS[t][0]}</b> (${TRAITS[t][1]})`).join("; ")}</p>`,[{t:"Back",cls:"hi",f:hub}]);}
function standingsScreen(sid,all){if(!sid||!SER[sid])sid="cup";const s=SER[sid];const st=G.S[sid];const rows=standings(sid);const lim=all?rows.length:Math.min(rows.length,40);
 const tb=rows.slice(0,lim).map((r,i)=>{const d=G.D[r.id];const tm=r.id==="me"?G.car.tm:d&&d.tm;return {cells:[i+1+(st.chase&&st.chase.indexOf(r.id)>=0?"*":""),r.id==="me"?`<b>${esc(G.me.name)}</b>`:esc(nm(r.id)),esc(tm?tn(tm):"-"),r.p,r.st,r.w,r.t5,r.pol,r.dnf],hl:r.id==="me"};});
 const ch=[{t:"Calendar & results",f:()=>calendarScreen(sid)},{t:"Past champions",f:()=>champsScreen(sid)},{t:"Teams & drivers",f:()=>seriesDetail(sid)}];if(!all&&rows.length>lim)ch.push({t:"Show the full field",f:()=>standingsScreen(sid,1)});
 const mine=[...new Set([G.car.s].concat(G.st.races.filter(r=>r.yr===G.yr).map(r=>r.s)).concat((G.own||[]).map(o=>o.s)))].filter(x=>x&&x!==sid&&!SER[x].oneoff);mine.forEach(x=>ch.push({t:`${esc(SER[x].sh)} standings`,f:()=>standingsScreen(x)}));
 ch.push({t:"Other series",f:()=>pickSeries(standingsScreen)},{t:"Back",cls:"hi",f:hub});
 show(`<h2>${esc(s.n)} ${G.yr}</h2><p>${st.res.length} of ${s.cal.length} rounds complete${st.chase?" · Chase drivers marked *":""}${st.done&&st.champ?` · Champion: <b>${esc(st.champ==="me"?G.me.name:nm(st.champ))}</b>`:""}</p>${table(["Pos","Driver","Team","Pts","St","W","T5","Pole","DNF"],tb)}`,ch);}
function pickSeries(fn){const ch=[];Object.keys(LADDERS).forEach(l=>{let first=true;SERIES_LIST.filter(s=>s.lad===l&&!s.oneoff).forEach(s=>{ch.push({sec:first?LADDERS[l].toUpperCase():null,t:esc(s.n),f:()=>fn(s.id)});first=false;});});
 show(`<h2>Pick a series</h2>`,ch.concat([{t:"Back",cls:"hi",f:hub}]));}
function calendarScreen(sid){if(!sid||!SER[sid])sid="cup";const s=SER[sid];const st=G.S[sid];
 const rows=s.cal.map((c,ci)=>{const r=st.res.find(x=>x.ci===ci);const mine=G.st.races.find(x=>x.yr===G.yr&&x.s===sid&&x.ci===ci);return {cells:[ci+1,wkDate(c[1]),esc(c[2]||evName(sid,ci))+(c[3]?" 👑":""),esc(tkn(c[0])),r?(r.w==="me"?`<b>${esc(G.me.name)}</b>`:esc(nm(r.w))):s.oneoff&&G.hist[sid].find(h=>h.yr===G.yr)?esc(G.hist[sid].find(h=>h.yr===G.yr).cn):"",mine?ordinal(mine.f):""],hl:!!mine&&mine.f===1};});
 show(`<h2>${esc(s.sh)} calendar ${G.yr}</h2>${table(["Rd","Date","Event","Track","Winner","You"],rows)}`,[{t:"Standings",f:()=>standingsScreen(sid)},{t:"Back",cls:"hi",f:hub}]);}
function champsScreen(sid){const h=G.hist[sid]||[];show(`<h2>${esc(SER[sid].sh)}: champions${SER[sid].oneoff?" & winners":""}</h2>${table(["Year","Champion","Team"],h.slice().reverse().map(x=>({cells:[x.yr,x.c==="me"?`<b>${esc(G.me.name)}</b>`:esc(x.c&&G.D[x.c]?nm(x.c):x.cn),esc(x.tm||"")],hl:x.c==="me"})))}`,[{t:"Back",cls:"hi",f:()=>standingsScreen(sid)}]);}
function seriesBrowser(){pickSeries(seriesDetail);}
function seriesDetail(sid){const s=SER[sid];const tms=teamsOf(sid).sort((a,b)=>b.q-a.q);
 const rows=[];tms.forEach(t=>t.cars.forEach(c=>{if(!c.d)return;rows.push({cells:["#"+esc(String(c.num)),c.d==="me"?`<b>${esc(G.me.name)}</b>`:esc(nm(c.d)),esc(tn(t.id))+(t.own?" (yours)":""),esc(t.mfr||""),c.d==="me"?Math.round(OVR(s.disc)):Math.round(G.D[c.d].o),c.d==="me"?G.me.age:G.yr-G.D[c.d].by],hl:c.d==="me"});}));
 show(`<h2>${esc(s.n)}</h2><p>${esc(s.desc)}</p>${tiles([{l:"Ladder",v:esc(LADDERS[s.lad]||""),sm:1},{l:"Level",v:esc(seriesTierName(s.tier)),sm:1},{l:"Races",v:s.cal.length},{l:"Field",v:s.field},{l:"Min age",v:s.age},{l:"Season cost",v:s.cost?money(s.cost):"Team-funded",sm:1}])}
 ${s.oneoff?"":table(["Car","Driver","Team","Make","Rtg","Age"],rows)}`,[{t:"Standings",f:()=>standingsScreen(sid)},{t:"Calendar",f:()=>calendarScreen(sid)},{t:"Past champions",f:()=>champsScreen(sid)},{t:"Other series",f:seriesBrowser},{t:"Back",cls:"hi",f:hub}]);}
function newsScreen(){const n=G.news.slice(0,70);const rum=G.rumors.filter(r=>r.yr===G.yr&&!r.me).slice(-8).reverse();
 show(`<h2>News &amp; rumors</h2>${rum.length?`<h3>Silly season rumor mill</h3><ul>${rum.map(r=>`<li>${esc(nm(r.d))} ↔ ${esc(tn(r.tm))}</li>`).join("")}</ul>`:""}<div class="news">${n.map(x=>`<div class="${x.m?"mine":""}"><span class="dim">${dateLbl(x.yr,x.wk)}</span> ${esc(x.t)}</div>`).join("")||"<p>No news yet.</p>"}</div>`,[{t:"Back",cls:"hi",f:hub}]);}
function relScreen(){const keys=Object.keys(G.rel).filter(k=>Math.abs(G.rel[k])>=1).sort((a,b)=>G.rel[b]-G.rel[a]);
 show(`<h2>Relationships</h2><p>People remember. Team owners, rivals, crew chiefs, sponsors and the media all react to how you treat them.</p>${table(["Who","Standing"],keys.map(k=>[esc(relName(k)),relTag(k)]))}`,[{t:"Back",cls:"hi",f:hub}]);}
/* ---------- achievements ---------- */
const ACH=[["first_start","Green Flag","Make your first start",()=>G.st.races.length>0],["first_win","Victory Lane","Win your first race",()=>G.st.races.some(r=>r.f===1)],["first_pole","Pole Sitter","Win a pole",()=>G.st.races.some(r=>r.st===1)],["podium","Champagne","Finish on the podium",()=>G.st.races.some(r=>r.f<=3)],
 ["w10","Double Digits","Win 10 races",()=>careerTotals().w>=10],["w25","Winner","Win 25 races",()=>careerTotals().w>=25],["w50","Serial Winner","Win 50 races",()=>careerTotals().w>=50],["w100","Centurion","Win 100 races",()=>careerTotals().w>=100],
 ["s100","Ironman","Make 100 starts",()=>G.st.races.length>=100],["s500","Lifer","Make 500 starts",()=>G.st.races.length>=500],
 ["title1","Champion","Win a championship",()=>G.st.titles.length>=1],["title3","Dynasty","Win 3 championships",()=>G.st.titles.length>=3],["title5","Legend","Win 5 championships",()=>G.st.titles.length>=5],["title3s","Versatile Champion","Win titles in 3 different series",()=>new Set(G.st.titles.map(t=>t.s)).size>=3],
 ["disc3","Jack of All Trades","Win in 3 different disciplines",()=>new Set(G.st.races.filter(r=>r.f===1).map(r=>SER[r.s].disc)).size>=3],
 ["d500","Great American Race","Win the Daytona 500",()=>G.st.cj.some(c=>/Daytona 500/.test(c.ev))],["i500","Milk Drinker","Win the Indianapolis 500",()=>G.st.cj.some(c=>/Indianapolis 500/.test(c.ev))],["monaco","Monte Carlo","Win the Monaco Grand Prix",()=>G.st.cj.some(c=>/Monaco/.test(c.ev))],["lemans","Twice Around the Clock","Win the 24 Hours of Le Mans",()=>G.st.cj.some(c=>/Le Mans/.test(c.ev))],
 ["triple","Triple Crown","Win Monaco, Indy and Le Mans",()=>["Monaco","Indianapolis 500","Le Mans"].every(k=>G.st.cj.some(c=>c.ev.indexOf(k)>=0))],["chili","Golden Driller","Win the Chili Bowl",()=>G.st.cj.some(c=>/Chili/.test(c.ev))],["knox","Knoxville King","Win the Knoxville Nationals",()=>G.st.cj.some(c=>/Knoxville/.test(c.ev))],["snow","Snowball Champion","Win the Snowball Derby",()=>G.st.cj.some(c=>/Snowball/.test(c.ev))],["bathurst","King of the Mountain","Win the Bathurst 1000",()=>G.st.cj.some(c=>/Bathurst/.test(c.ev))],
 ["double","The Double","Race the Indy 500 and the Coca-Cola 600 in the same year",()=>G.st.races.some(r=>/Indianapolis 500/.test(r.ev)&&G.st.races.some(x=>x.yr===r.yr&&/Coca-Cola 600/.test(x.ev)))],
 ["f1","Formula 1 Driver","Start a Formula 1 race",()=>G.st.races.some(r=>r.s==="f1")],["cup","Cup Driver","Start a NASCAR Cup race",()=>G.st.races.some(r=>r.s==="cup")],["indy","IndyCar Driver","Start an IndyCar race",()=>G.st.races.some(r=>r.s==="indycar")],
 ["owner","Team Owner","Own a race team",()=>(G.own||[]).length>0||(G.ownHist||[]).length>0],["ownwin","Owner's Win","Win a race as a team owner",()=>(G.own||[]).some(o=>o.wins>0)||(G.ownHist||[]).some(o=>o.wins>0)],["owntitle","Owner's Championship","Win a title as a team owner",()=>(G.own||[]).some(o=>o.titles>0)||(G.ownHist||[]).some(o=>o.titles>0)],
 ["ownerdriver","Owner-Driver Winner","Win driving your own team's car",()=>G.st.races.some(r=>r.f===1&&(G.own||[]).some(o=>o.n===r.tmn))],
 ["rain","Rainmaster","Win a wet race",()=>G.st.races.some(r=>r.f===1&&r.wet)],["back","From the Back","Win from 20th or worse",()=>G.st.races.some(r=>r.f===1&&r.st>=20)],["mil","Millionaire","Earn $1,000,000",()=>G.me.earned>=1e6],["mil10","Big Money","Earn $10,000,000",()=>G.me.earned>=1e7],
 ["sponsor","Backed","Sign a sponsor",()=>G.car.spons.length>0],["slp","Superlicense","Hold 40 superlicense points",()=>slpTotal()>=40],["seasons20","Two Decades","Race 20 seasons",()=>new Set(G.st.races.map(r=>r.yr)).size>=20],["hof","Hall of Famer","Be inducted into the Hall of Fame",()=>!!G.fl.hof]];
function checkAch(){if(!G||!G.me)return;G.fl.peakOvr=Math.max(G.fl.peakOvr||0,OVR());ACH.forEach(a=>{if(G.ach[a[0]])return;let ok=false;try{ok=a[3]();}catch(e){ok=false;}if(ok){G.ach[a[0]]=G.yr;G.notes.push(`🏅 Achievement unlocked: <b>${a[1]}</b>`);}});}
function achScreen(){const n=Object.keys(G.ach).length;show(`<h2>Achievements (${n}/${ACH.length})</h2>${table(["","Achievement","How"],ACH.map(a=>({cells:[G.ach[a[0]]?"🏅":"·",G.ach[a[0]]?`<b>${a[1]}</b> (${G.ach[a[0]]})`:a[1],a[2]],hl:!!G.ach[a[0]]})))}`,[{t:"Back",cls:"hi",f:careerScreen}]);}
/* ---------- retirement & endings ---------- */
function retireMenu(){const m=G.me;if(m.retired)return show(`<h2>Close the book?</h2><p>This ends the game and shows your final career summary and legacy.</p>`,[{t:"Yes, end my career story",cls:"hi",f:()=>{G.over=true;save();endScreen();}},{t:"Not yet",f:hub}]);
 show(`<h2>Retire from driving?</h2><p>You're ${m.age}. ${m.age<30?"That's young to walk away.":m.age>=40?"Nobody would blame you.":"You still have years left."}</p>`,[
  {t:"Retire and end the game",sub:"Final career summary, Hall of Fame vote and legacy",f:()=>{doRetire();G.over=true;save();endScreen();}},
  {t:"Retire from driving, keep owning teams",sub:(G.own||[]).length?"Stay on as a full-time owner":"You don't own a team yet; you can start one after retiring",f:()=>{doRetire();save();hub();}},
  {t:"Keep racing",cls:"hi",f:hub}]);}
function doRetire(){const m=G.me;m.retired=true;removeMe();G.car.con=null;G.car.next=null;G.car.s=null;G.car.tm=null;G.car.role=null;G.offers=[];addNews(`${m.name} retires from driving at age ${m.age}.`,true);}
function hofCheck(){const ls=legacyScore();const topTitles=G.st.titles.filter(t=>SER[t.s].tier>=8).length;const ok=ls>=320||topTitles>=2||(topTitles>=1&&ls>=200)||G.st.cj.length>=3;if(ok)G.fl.hof=1;return ok;}
function endScreen(){G.over=true;const m=G.me;const c=careerTotals();const hof=hofCheck();checkAch();const ls=legacyScore();save();
 const tops=G.st.titles.map(t=>`${t.yr} ${esc(SER[t.s].n)}`);const cj=G.st.cj.map(x=>`${x.yr} ${esc(x.ev)}`);
 const story=c.st===0?"A career that never quite got started.":ls>=550?`${esc(m.name)} will be talked about as long as engines are fired. A legend of the sport.`:ls>=320?`A champion and a star. ${esc(m.name)}'s name is on trophies that matter.`:ls>=170?"A proven winner who earned respect everywhere they raced.":ls>=80?"A respected professional who made a living doing what most people only dream about.":"From Saturday nights to wherever the road led, a racer's racer.";
 show(`<div class="eyebrow">CAREER COMPLETE</div><h2>${esc(m.name)}</h2><p>${story}</p>
 ${tiles([{l:"Legacy score",v:ls,h:legacyTier(ls)},{l:"Hall of Fame",v:hof?"Inducted ✅":"Not inducted",sm:1},{l:"Starts",v:c.st},{l:"Wins",v:c.w},{l:"Podiums",v:c.pod},{l:"Poles",v:c.pol},{l:"Titles",v:G.st.titles.length},{l:"Crown jewels",v:G.st.cj.length},{l:"Earnings",v:money(m.earned),sm:1},{l:"Achievements",v:Object.keys(G.ach).length+"/"+ACH.length,sm:1}])}
 ${tops.length?`<h3>Championships</h3><p>${tops.join("<br>")}</p>`:""}${cj.length?`<h3>Crown jewels</h3><p>${cj.join("<br>")}</p>`:""}
 ${(G.ownHist||[]).length||(G.own||[]).length?`<h3>As a team owner</h3><p>${(G.own||[]).concat(G.ownHist||[]).map(o=>`${esc(o.n)} (${esc(SER[o.s].sh)}): ${o.wins} wins, ${o.titles} titles`).join("<br>")}</p>`:""}
 ${more(table(["Year","Series","St","W","T5","Pos"],G.st.seasons.map(s=>[s.yr,esc(SER[s.s].sh),s.st,s.w,s.t5,s.oo?"-":(s.pos?ordinal(s.pos):"-")])),"Season by season")}`,[
  {t:"Career stats",f:careerScreen},{t:"Export this save",f:backupScreen},{t:"Start a new career",cls:"hi",f:()=>{G=null;try{localStorage.removeItem(SAVE_KEY);}catch(e){}newCareer();}},{t:"Title screen",f:title}]);}
